import type {
  RuntimeRenderDiagnostics,
  RuntimeRenderDiagnosticsStats,
} from './index.runtimeEvents.types.ts'

export function resolveRuntimeRenderDiagnosticsStats(
  diagnostics: RuntimeRenderDiagnostics,
): RuntimeRenderDiagnosticsStats {
  return {
    performance: {
      timing: {
        frameStageId: diagnostics.frameStageId,
        frameStageSequence: diagnostics.frameStageSequence,
        frameStageIssuedAtMs: diagnostics.frameStageIssuedAtMs,
        frameStageSchedulerMode: diagnostics.frameStageSchedulerMode,
        frameStageSceneApplyMode: diagnostics.frameStageSceneApplyMode,
        drawMs: diagnostics.drawMs,
        scenePrepareMs: diagnostics.scenePrepareMs,
        sceneApplyMs: diagnostics.sceneApplyMs,
        viewportCommitMs: diagnostics.viewportCommitMs,
        viewportResizeMs: diagnostics.viewportResizeMs,
        viewportStateUpdateMs: diagnostics.viewportStateUpdateMs,
        diagnosticsPublishMs: diagnostics.diagnosticsPublishMs,
        plannerSampleMs: diagnostics.plannerSampleMs,
        schedulerQueueWaitMs: diagnostics.schedulerQueueWaitMs,
        schedulerThrottleDelayMs: diagnostics.schedulerThrottleDelayMs,
        presentRafDelayMs: diagnostics.presentRafDelayMs,
        fpsInstantaneous: diagnostics.fpsInstantaneous,
        fpsEstimate: diagnostics.fpsEstimate,
        fpsPeak: diagnostics.fpsPeak,
        fpsEstimatePeak: diagnostics.fpsEstimatePeak,
        fpsReached60: diagnostics.fpsReached60,
        fpsReached120: diagnostics.fpsReached120,
      },
      lod: {
        engineFrameQuality: diagnostics.engineFrameQuality,
        renderPolicyQuality: diagnostics.renderPolicyQuality,
        renderPolicyDpr: diagnostics.renderPolicyDpr,
        sideTargetDpr: diagnostics.sideTargetDpr,
        outputDpr: diagnostics.outputDpr,
        renderPhase: diagnostics.renderPhase,
        viewportInteractionType: diagnostics.viewportInteractionType,
        overlayMode: diagnostics.overlayMode,
      },
      cache: {
        cacheMode: diagnostics.cacheMode,
        cacheHitCount: diagnostics.cacheHitCount,
        cacheMissCount: diagnostics.cacheMissCount,
        frameReuseHitCount: diagnostics.frameReuseHitCount,
        frameReuseMissCount: diagnostics.frameReuseMissCount,
        cacheFallbackReason: diagnostics.cacheFallbackReason,
      },
      webgl: {
        webglRenderPath: diagnostics.webglRenderPath,
        webgpuRenderPath: diagnostics.webgpuRenderPath,
        webgpuNativeSubmissionAttemptedCount:
          diagnostics.webgpuNativeSubmissionAttemptedCount,
        webgpuNativeSubmissionSuccessCount:
          diagnostics.webgpuNativeSubmissionSuccessCount,
        webgpuNativeSubmissionFailureCount:
          diagnostics.webgpuNativeSubmissionFailureCount,
        webgpuNativeSubmissionTotalCount:
          diagnostics.webgpuNativeSubmissionTotalCount,
        webgpuNativeSubmissionTotalFailureCount:
          diagnostics.webgpuNativeSubmissionTotalFailureCount,
        webgpuNativeRectBatchEligibleCount:
          diagnostics.webgpuNativeRectBatchEligibleCount,
        webgpuNativeRectBatchRejectedReason:
          diagnostics.webgpuNativeRectBatchRejectedReason,
        webglFeatureCapabilityGateReason:
          diagnostics.webglFeatureCapabilityGateReason,
        webgpuFeatureCapabilityGateReason:
          diagnostics.webgpuFeatureCapabilityGateReason,
        webglInteractiveTextFallbackCount: diagnostics.webglInteractiveTextFallbackCount,
        webglImageTextureUploadCount: diagnostics.webglImageTextureUploadCount,
        webglImageTextureUploadBytes: diagnostics.webglImageTextureUploadBytes,
        webglImageDownsampledUploadCount: diagnostics.webglImageDownsampledUploadCount,
        webglImageDownsampledUploadBytesSaved: diagnostics.webglImageDownsampledUploadBytesSaved,
        webglDeferredImageTextureCount: diagnostics.webglDeferredImageTextureCount,
        webglTextTextureUploadCount: diagnostics.webglTextTextureUploadCount,
        webglTextTextureUploadBytes: diagnostics.webglTextTextureUploadBytes,
        webglTextCacheHitCount: diagnostics.webglTextCacheHitCount,
        webglPrecomputedTextCacheKeyCount: diagnostics.webglPrecomputedTextCacheKeyCount,
        webglFallbackTextCacheKeyCount: diagnostics.webglFallbackTextCacheKeyCount,
        webglFrameReuseEdgeRedrawCount: diagnostics.webglFrameReuseEdgeRedrawCount,
        webglCompositeUploadBytes: diagnostics.webglCompositeUploadBytes,
        l0PreviewHitCount: diagnostics.l0PreviewHitCount,
        l0PreviewMissCount: diagnostics.l0PreviewMissCount,
        l1CompositeHitCount: diagnostics.l1CompositeHitCount,
        l1CompositeMissCount: diagnostics.l1CompositeMissCount,
        l2TileHitCount: diagnostics.l2TileHitCount,
        l2TileMissCount: diagnostics.l2TileMissCount,
        webglPreviewReuseMs: diagnostics.webglPreviewReuseMs,
        webglPlanBuildMs: diagnostics.webglPlanBuildMs,
        webglTextureUploadMs: diagnostics.webglTextureUploadMs,
        webglDrawSubmitMs: diagnostics.webglDrawSubmitMs,
        webglSnapshotCaptureMs: diagnostics.webglSnapshotCaptureMs,
        webglModelRenderMs: diagnostics.webglModelRenderMs,
        webglPreviewExecutionMode: diagnostics.webglPreviewExecutionMode,
        webglPreviewExecutionSource: diagnostics.webglPreviewExecutionSource,
        webglBudgetPressure: diagnostics.webglBudgetPressure,
        webglBudgetPressureReason: diagnostics.webglBudgetPressureReason,
        webglBudgetPressureSource: diagnostics.webglBudgetPressureSource,
        webglDrawSubmitBudgetMs: diagnostics.webglDrawSubmitBudgetMs,
        webglTextureUploadBudgetBytes: diagnostics.webglTextureUploadBudgetBytes,
        webglTextureUploadTotalBudgetBytes: diagnostics.webglTextureUploadTotalBudgetBytes,
        webglImageTextureUploadBudgetCount: diagnostics.webglImageTextureUploadBudgetCount,
        webglTextTextureUploadBudgetCount: diagnostics.webglTextTextureUploadBudgetCount,
        webglTilePreloadBudgetMs: diagnostics.webglTilePreloadBudgetMs,
        webglTilePreloadBudgetUploads: diagnostics.webglTilePreloadBudgetUploads,
        webglOverlayPassBudgetMs: diagnostics.webglOverlayPassBudgetMs,
        webglDrawSubmitBudgetExceeded: diagnostics.webglDrawSubmitBudgetExceeded,
        webglTextureUploadBudgetExceeded: diagnostics.webglTextureUploadBudgetExceeded,
        webglOverlayBudgetExceeded: diagnostics.webglOverlayBudgetExceeded,
        webglPredictorDirectionX: diagnostics.webglPredictorDirectionX,
        webglPredictorDirectionY: diagnostics.webglPredictorDirectionY,
        webglPredictorSpeedPxPerSec: diagnostics.webglPredictorSpeedPxPerSec,
        webglPredictorConfidence: diagnostics.webglPredictorConfidence,
        webglPredictorPreloadRing: diagnostics.webglPredictorPreloadRing,
        webglPredictorOverscanCssPx: diagnostics.webglPredictorOverscanCssPx,
        webglPredictivePreloadEnqueueCount: diagnostics.webglPredictivePreloadEnqueueCount,
        webglPredictivePreloadProcessedCount: diagnostics.webglPredictivePreloadProcessedCount,
        webglPredictivePreloadPrunedCount: diagnostics.webglPredictivePreloadPrunedCount,
        webglHighZoomTextSlaChecked: diagnostics.webglHighZoomTextSlaChecked,
        webglHighZoomTextSlaScale: diagnostics.webglHighZoomTextSlaScale,
        webglHighZoomTextSlaViolationCount: diagnostics.webglHighZoomTextSlaViolationCount,
        webglDeferredTextTextureCount: diagnostics.webglDeferredTextTextureCount,
        panScheduleRequestCount: diagnostics.panScheduleRequestCount,
        tileSynchronousRebuildCount: diagnostics.tileSynchronousRebuildCount,
        tileCacheSize: diagnostics.tileCacheSize,
        tileDirtyCount: diagnostics.tileDirtyCount,
        tileCacheTotalBytes: diagnostics.tileCacheTotalBytes,
        tileUploadCount: diagnostics.tileUploadCount,
        tileRenderCount: diagnostics.tileRenderCount,
        visibleTileCount: diagnostics.visibleTileCount,
        tileSchedulerPendingCount: diagnostics.tileSchedulerPendingCount,
        gpuTextureBytes: diagnostics.gpuTextureBytes,
        imageTextureBytes: diagnostics.imageTextureBytes,
        initialRenderPhase: diagnostics.initialRenderPhase,
        initialRenderProgress: diagnostics.initialRenderProgress,
        dirtyRegionCount: diagnostics.dirtyRegionCount,
        dirtyTileCount: diagnostics.dirtyTileCount,
        incrementalUpdateCount: diagnostics.incrementalUpdateCount,
        // Mirror flat LOD counters into sectioned stats for debug panel parity.
        hiddenCount: diagnostics.hiddenCount,
        pointCount: diagnostics.pointCount,
        blockCount: diagnostics.blockCount,
        bboxCount: diagnostics.bboxCount,
        simplifiedCount: diagnostics.simplifiedCount,
        normalCount: diagnostics.normalCount,
        fullCount: diagnostics.fullCount,
        shadowSkippedCount: diagnostics.shadowSkippedCount,
        filterSkippedCount: diagnostics.filterSkippedCount,
        thumbnailImageCount: diagnostics.thumbnailImageCount,
        fullImageCount: diagnostics.fullImageCount,
        groupThumbnailCount: diagnostics.groupThumbnailCount,
        lodDecisionTimeMs: diagnostics.lodDecisionTimeMs,
      },
    },
    planner: {
      frame: {
        framePlanVersion: diagnostics.framePlanVersion,
        framePlanCandidateCount: diagnostics.framePlanCandidateCount,
        framePlanSceneNodeCount: diagnostics.framePlanSceneNodeCount,
        framePlanVisibleRatio: diagnostics.framePlanVisibleRatio,
        framePlanShortlistActive: diagnostics.framePlanShortlistActive,
        framePlanShortlistCandidateRatio: diagnostics.framePlanShortlistCandidateRatio,
        framePlanShortlistAppliedCandidateCount: diagnostics.framePlanShortlistAppliedCandidateCount,
        framePlanShortlistPendingState: diagnostics.framePlanShortlistPendingState,
        framePlanShortlistPendingFrameCount: diagnostics.framePlanShortlistPendingFrameCount,
        framePlanShortlistToggleCount: diagnostics.framePlanShortlistToggleCount,
        framePlanShortlistDebounceBlockedToggleCount: diagnostics.framePlanShortlistDebounceBlockedToggleCount,
        framePlanShortlistEnterRatioThreshold: diagnostics.framePlanShortlistEnterRatioThreshold,
        framePlanShortlistLeaveRatioThreshold: diagnostics.framePlanShortlistLeaveRatioThreshold,
        framePlanShortlistStableFrameCount: diagnostics.framePlanShortlistStableFrameCount,
      },
      hit: {
        hitPlanVersion: diagnostics.hitPlanVersion,
        hitPlanCandidateCount: diagnostics.hitPlanCandidateCount,
        hitPlanHitCount: diagnostics.hitPlanHitCount,
        hitPlanExactCheckCount: diagnostics.hitPlanExactCheckCount,
      },
      dirtyRegion: {
        renderPrepDirtyCandidateCount: diagnostics.renderPrepDirtyCandidateCount,
        renderPrepDirtyOffscreenCount: diagnostics.renderPrepDirtyOffscreenCount,
        offscreenSceneDirtyForceRenderFrameThreshold: diagnostics.offscreenSceneDirtyForceRenderFrameThreshold,
        offscreenSceneDirtySkipConsecutiveCount: diagnostics.offscreenSceneDirtySkipConsecutiveCount,
        offscreenSceneDirtySkipConsecutiveMaxCount: diagnostics.offscreenSceneDirtySkipConsecutiveMaxCount,
        dirtyBoundsSmallAreaThreshold: diagnostics.dirtyBoundsSmallAreaThreshold,
        dirtyBoundsMediumAreaThreshold: diagnostics.dirtyBoundsMediumAreaThreshold,
        dirtyBoundsMarkCount: diagnostics.dirtyBoundsMarkCount,
        dirtyBoundsMarkArea: diagnostics.dirtyBoundsMarkArea,
        dirtyBoundsMarkSmallAreaCount: diagnostics.dirtyBoundsMarkSmallAreaCount,
        dirtyBoundsMarkMediumAreaCount: diagnostics.dirtyBoundsMarkMediumAreaCount,
        dirtyBoundsMarkLargeAreaCount: diagnostics.dirtyBoundsMarkLargeAreaCount,
      },
    },
    overlay: {
      overlayDegraded: diagnostics.overlayDegraded,
      overlayGuideInputCount: diagnostics.overlayGuideInputCount,
      overlayGuideKeptCount: diagnostics.overlayGuideKeptCount,
      overlayGuideDroppedCount: diagnostics.overlayGuideDroppedCount,
      overlayGuideSelectionStrategy: diagnostics.overlayGuideSelectionStrategy,
      overlayPathEditWhitelistActive: diagnostics.overlayPathEditWhitelistActive,
      overlayProjectionDiagnosticCount: diagnostics.overlayProjectionDiagnosticCount,
      overlayProjectionDiagnosticCodes: diagnostics.overlayProjectionDiagnosticCodes,
      overlayProjectionDiagnosticNodes: diagnostics.overlayProjectionDiagnosticNodes,
      activeOverlayScenePlane: diagnostics.activeOverlayScenePlane,
      activeOverlayOverlayPlane: diagnostics.activeOverlayOverlayPlane,
      activeOverlayUsesActivePlane: diagnostics.activeOverlayUsesActivePlane,
      activeOverlayProtectedNodeCount: diagnostics.activeOverlayProtectedNodeCount,
      activeOverlayInteractionActiveNodeCount:
        diagnostics.activeOverlayInteractionActiveNodeCount,
    },
    requests: {
      lastRenderRequestReason: diagnostics.lastRenderRequestReason,
      sceneDirtyRequestCount: diagnostics.sceneDirtyRequestCount,
      deferredImageDrainRequestCount: diagnostics.deferredImageDrainRequestCount,
      idleRedrawRequestCount: diagnostics.idleRedrawRequestCount,
      interactiveRequestCount: diagnostics.interactiveRequestCount,
      offscreenSceneDirtySkipRequestCount: diagnostics.offscreenSceneDirtySkipRequestCount,
      forcedSceneDirtyRequestCount: diagnostics.forcedSceneDirtyRequestCount,
    },
  }
}

/**
 * Returns the current runtime render diagnostics snapshot.
 */
