import type { EngineRenderFrame } from '../types/index.ts'
import {
  canReuseInteractiveTextTexture,
  canReuseTextTexture,
  copyCanvasRegion,
  drawInteractiveTextFallback,
  resolveImageTexture,
  resolvePacketTextureSourceRect,
  resolveTextCacheKey,
  resolveTextRasterScale,
  shouldSkipInteractiveTinyPacket,
  shouldSkipOverviewImagePacket,
  shouldSkipTextPlaceholderPacket,
  type CachedTextureEntry,
  type ImageUploadBudgetState,
} from './runtime/index.ts'
import { drawWebGLPacket } from './core/index.ts'
import {
  ENGINE_RENDER_FALLBACK_REASON,
  type EngineRenderFallbackReason,
} from '../fallbackTaxonomy/index.ts'
import { shouldPrioritizeInteractiveWebGLTexturePacket } from './webglFramePolicy.ts'
/**
 * Packet item shape consumed by WebGL packet submission loop.
 */
interface WebGLPacketSubmissionItem {
  /** Packet kind that decides texture and fallback behavior. */
  kind: 'shape' | 'text' | 'image'
  /** Scene node id associated with packet. */
  nodeId: string
  /** Optional precomputed text cache key from packet plan stage. */
  textCacheKey?: string
  /** Optional image asset id for image packets. */
  assetId?: string
  /** Packet world-space bounds. */
  worldBounds: { x: number; y: number; width: number; height: number }
  /** Packet color payload passed to shader pipeline. */
  color: readonly [number, number, number, number]
  /** Packet opacity payload passed to shader pipeline. */
  opacity: number
}

/**
 * Input contract for one WebGL packet submission pass.
 */
interface WebGLPacketSubmissionArgs {
  /** Active WebGL context. */
  context: WebGLRenderingContext
  /** Shared quad pipeline used by packet draw calls. */
  pipeline: Parameters<typeof drawWebGLPacket>[1]
  /** Effective frame consumed by submission logic. */
  effectiveFrame: EngineRenderFrame
  /** Packet list generated by packet planner. */
  packets: readonly WebGLPacketSubmissionItem[]
  /** Node id set used to route active-layer packets. */
  activeLayerNodeIdSet: ReadonlySet<string>
  /** Whether active-layer mask path is enabled for this frame. */
  activeLayerMaskEnabled: boolean
  /** Whether interaction lane is active for this frame. */
  interactionRenderLane: boolean
  /** Whether frame-level LOD degradation is enabled. */
  frameLodEnabled: boolean
  /** Whether text placeholder mode is active for this frame. */
  useTextPlaceholderMode: boolean
  /** Draw submit budget in milliseconds. */
  drawSubmitBudgetMs: number
  /** Per-frame image upload count budget. */
  imageTextureUploadMaxCount: number
  /** Per-frame image upload byte budget. */
  textureUploadBudgetBytes: number
  /** Per-frame total texture upload byte budget. */
  textureUploadTotalBudgetBytes: number
  /** Per-frame text texture upload count budget. */
  textTextureUploadMaxCount: number
  /** High-zoom text SLA threshold scale. */
  highZoomTextSlaScale: number
  /** Bytes-per-pixel constant for texture byte estimation. */
  textureBytesPerPixel: number
  /** Image cache map shared by renderer instance. */
  imageCache: Map<string, CachedTextureEntry>
  /** Text cache map shared by renderer instance. */
  textCache: Map<string, CachedTextureEntry>
  /** Resource budget tracker used by cache and texture accounting. */
  resourceBudget: Parameters<typeof resolveImageTexture>[5]
  /** Model surface canvas used for text crop uploads. */
  modelSurfaceCanvas: HTMLCanvasElement | OffscreenCanvas
  /** Scratch canvas used for text region cropping before upload. */
  textCropSurfaceCanvas: HTMLCanvasElement | OffscreenCanvas
  /** Current cache fallback reason before packet submission. */
  cacheFallbackReason: EngineRenderFallbackReason
}

/**
 * Packet submission result for one render frame.
 */
interface WebGLPacketSubmissionResult {
  /** Total draw calls submitted during packet loop. */
  drawCount: number
  /** Number of interaction text fallback draws. */
  interactiveTextFallbackCount: number
  /** Number of uploaded text textures. */
  textTextureUploadCount: number
  /** Uploaded text texture bytes. */
  textTextureUploadBytes: number
  /** Number of text cache hits. */
  textCacheHitCount: number
  /** Number of uploaded image textures. */
  imageTextureUploadCount: number
  /** Uploaded image texture bytes. */
  imageTextureUploadBytes: number
  /** Number of downsampled image uploads. */
  imageDownsampledUploadCount: number
  /** Saved bytes due to downsampled image uploads. */
  imageDownsampledUploadBytesSaved: number
  /** Number of deferred image texture uploads. */
  deferredImageTextureCount: number
  /** Number of deferred text texture uploads. */
  deferredTextTextureCount: number
  /** Combined image+text uploaded texture bytes. */
  totalTextureUploadBytes: number
  /** Texture upload duration accumulated in packet loop. */
  textureUploadMs: number
  /** Draw submit duration (excluding texture upload slice). */
  drawSubmitMs: number
  /** Whether draw submit budget was exceeded. */
  drawSubmitBudgetExceeded: boolean
  /** Whether texture budget was exceeded. */
  textureUploadBudgetExceeded: boolean
  /** Whether high-zoom text SLA check executed. */
  highZoomTextSlaChecked: boolean
  /** Number of high-zoom text SLA violations. */
  highZoomTextSlaViolationCount: number
  /** Fallback reason after packet submission updates. */
  cacheFallbackReason: EngineRenderFallbackReason
}

/**
 * Submits packet plan for one frame and returns packet-path metrics and budget flags.
 * @param args One-frame packet submission input bundle.
 * @returns Submission counters, timing slices, budget flags, and fallback reason updates.
 */
export function submitWebGLPacketSequence(
  args: WebGLPacketSubmissionArgs,
): WebGLPacketSubmissionResult {
  let drawCount = 0
  let interactiveTextFallbackCount = 0
  let textTextureUploadCount = 0
  let textTextureUploadBytes = 0
  let textCacheHitCount = 0
  let imageTextureUploadCount = 0
  let imageTextureUploadBytes = 0
  let imageDownsampledUploadCount = 0
  let imageDownsampledUploadBytesSaved = 0
  let deferredImageTextureCount = 0
  let deferredTextTextureCount = 0
  let totalTextureUploadBytes = 0
  let textureUploadMs = 0
  let cacheFallbackReason = args.cacheFallbackReason
  let drawSubmitBudgetExceeded = false
  let highZoomTextSlaChecked = false
  let highZoomTextSlaViolationCount = 0

  let remainingTextTextureUploadCount = args.textTextureUploadMaxCount
  let remainingTotalTextureUploadBytes = args.textureUploadTotalBudgetBytes
  const imageUploadBudget: ImageUploadBudgetState = {
    remainingUploads: args.imageTextureUploadMaxCount,
    remainingBytes: args.textureUploadBudgetBytes,
  }

  const packetLoopStart = performance.now()
  const basePackets = args.activeLayerMaskEnabled
    ? args.packets.filter((packet) => !args.activeLayerNodeIdSet.has(packet.nodeId))
    : args.packets
  const activePackets = args.activeLayerMaskEnabled
    ? args.packets.filter((packet) => args.activeLayerNodeIdSet.has(packet.nodeId))
    : []
  const interactionDirtyRegions = args.effectiveFrame.context.dirtyRegions
  const activePacketsInDirtyRegions = activePackets.filter((packet) => {
    if (!interactionDirtyRegions || interactionDirtyRegions.length === 0) {
      return true
    }

    // Keep active redraw constrained to dirty regions so transform preview stays live.
    const packetMinX = packet.worldBounds.x
    const packetMinY = packet.worldBounds.y
    const packetMaxX = packet.worldBounds.x + packet.worldBounds.width
    const packetMaxY = packet.worldBounds.y + packet.worldBounds.height
    return interactionDirtyRegions.some((dirtyRegion) => {
      const dirtyBounds = dirtyRegion.bounds
      const dirtyMinX = dirtyBounds.x
      const dirtyMinY = dirtyBounds.y
      const dirtyMaxX = dirtyBounds.x + dirtyBounds.width
      const dirtyMaxY = dirtyBounds.y + dirtyBounds.height
      return (
        packetMaxX >= dirtyMinX &&
        packetMinX <= dirtyMaxX &&
        packetMaxY >= dirtyMinY &&
        packetMinY <= dirtyMaxY
      )
    })
  })
  const packetSubmissionSequence = args.activeLayerMaskEnabled
    ? [...basePackets, ...activePacketsInDirtyRegions]
    : basePackets

  for (const packet of packetSubmissionSequence) {
    const activeLayerPass = args.activeLayerNodeIdSet.has(packet.nodeId)
    // Break packet submission once draw budget is exceeded after at least
    // one draw, then rely on snapshot/tile/model fallback on next frame.
    if (
      !activeLayerPass &&
      drawCount > 0 &&
      performance.now() - packetLoopStart >= args.drawSubmitBudgetMs
    ) {
      drawSubmitBudgetExceeded = true
      cacheFallbackReason = cacheFallbackReason === ENGINE_RENDER_FALLBACK_REASON.NONE
        ? ENGINE_RENDER_FALLBACK_REASON.L3_BUDGET_DRAW_SUBMIT_CAP
        : cacheFallbackReason
      break
    }

    if (
      !activeLayerPass &&
      args.interactionRenderLane &&
      shouldSkipInteractiveTinyPacket(args.effectiveFrame, packet.kind, packet.worldBounds)
    ) {
      // Skip imperceptible packets in interaction fallback to preserve frame budget.
      continue
    }

    if (packet.kind === 'image' && packet.assetId) {
      if (!activeLayerPass && shouldSkipOverviewImagePacket(args.effectiveFrame, packet.worldBounds, args.frameLodEnabled)) {
        continue
      }

      const imageTexture = resolveImageTexture(
        args.context,
        args.effectiveFrame,
        packet.worldBounds,
        packet.assetId,
        args.imageCache,
        args.resourceBudget,
        imageUploadBudget,
        args.interactionRenderLane
          ? shouldPrioritizeInteractiveWebGLTexturePacket(args.effectiveFrame, packet, activeLayerPass)
          : false,
      )
      textureUploadMs += imageTexture.uploadMs
      if (imageTexture.deferred) {
        deferredImageTextureCount += 1
      }
      imageTextureUploadCount += imageTexture.uploadCount
      imageTextureUploadBytes += imageTexture.uploadBytes
      totalTextureUploadBytes += imageTexture.uploadBytes
      remainingTotalTextureUploadBytes = Math.max(
        0,
        remainingTotalTextureUploadBytes - imageTexture.uploadBytes,
      )
      imageDownsampledUploadCount += imageTexture.downsampledUploadCount
      imageDownsampledUploadBytesSaved += imageTexture.downsampledBytesSaved
      drawCount += drawWebGLPacket(
        args.context,
        args.pipeline,
        args.effectiveFrame,
        packet.worldBounds,
        packet.color,
        packet.opacity,
        imageTexture.texture,
      )
      continue
    }

    if (packet.kind === 'text') {
      const cached = args.textCache.get(packet.nodeId)
      const textCacheKey = resolveTextCacheKey(packet)
      const textRasterScale = resolveTextRasterScale(args.effectiveFrame)

      if (args.useTextPlaceholderMode) {
        // Low-zoom text is not legible at glyph fidelity.
        if (shouldSkipTextPlaceholderPacket(args.effectiveFrame, packet.worldBounds, args.frameLodEnabled)) {
          continue
        }

        interactiveTextFallbackCount += 1
        drawCount += drawInteractiveTextFallback(
          args.context,
          args.pipeline,
          args.effectiveFrame,
          packet.worldBounds,
          packet.color,
          packet.opacity,
        )
        continue
      }

      if (args.interactionRenderLane) {
        // Interactive mode prefers cached text textures when content is
        // unchanged so pan/zoom previews avoid collapsing to solid blocks.
        if (cached && canReuseInteractiveTextTexture(cached, textCacheKey)) {
          textCacheHitCount += 1
          args.resourceBudget.markTextureUsed(packet.nodeId)
          drawCount += drawWebGLPacket(
            args.context,
            args.pipeline,
            args.effectiveFrame,
            packet.worldBounds,
            packet.color,
            packet.opacity,
            cached.texture,
          )
          continue
        }

        const shouldUploadCriticalText = shouldPrioritizeInteractiveWebGLTexturePacket(
          args.effectiveFrame,
          packet,
          activeLayerPass,
        )
        if (!shouldUploadCriticalText) {
          // Avoid texture uploads during interaction for non-critical packets.
          interactiveTextFallbackCount += 1
          drawCount += drawInteractiveTextFallback(
            args.context,
            args.pipeline,
            args.effectiveFrame,
            packet.worldBounds,
            packet.color,
            packet.opacity,
          )
          continue
        }
      }

      // Try cached text texture first
      if (cached && canReuseTextTexture(cached, textCacheKey, textRasterScale)) {
        textCacheHitCount += 1
        args.resourceBudget.markTextureUsed(packet.nodeId)
        drawCount += drawWebGLPacket(
          args.context,
          args.pipeline,
          args.effectiveFrame,
          packet.worldBounds,
          packet.color,
          packet.opacity,
          cached.texture,
        )
        continue
      }

      if (remainingTextTextureUploadCount <= 0 || remainingTotalTextureUploadBytes <= 0) {
        // Defer text texture upload when this frame exhausted text/total budget.
        deferredTextTextureCount += 1
        interactiveTextFallbackCount += 1
        drawCount += drawInteractiveTextFallback(
          args.context,
          args.pipeline,
          args.effectiveFrame,
          packet.worldBounds,
          packet.color,
          packet.opacity,
        )
        continue
      }

      const textureSourceRect = resolvePacketTextureSourceRect(
        packet.worldBounds,
        args.effectiveFrame,
      )
      const textUploadBytesEstimate = textureSourceRect.width * textureSourceRect.height * args.textureBytesPerPixel
      if (textUploadBytesEstimate > remainingTotalTextureUploadBytes) {
        // Defer oversized text uploads when combined image+text budget is exhausted.
        deferredTextTextureCount += 1
        interactiveTextFallbackCount += 1
        drawCount += drawInteractiveTextFallback(
          args.context,
          args.pipeline,
          args.effectiveFrame,
          packet.worldBounds,
          packet.color,
          packet.opacity,
        )
        continue
      }

      const cropped = copyCanvasRegion(
        args.modelSurfaceCanvas,
        args.textCropSurfaceCanvas,
        textureSourceRect.x,
        textureSourceRect.y,
        textureSourceRect.width,
        textureSourceRect.height,
      )
      const texture = cached?.texture ?? args.context.createTexture()
      if (texture) {
        const reusesCachedTexture = cached?.texture === texture
        args.context.bindTexture(args.context.TEXTURE_2D, texture)
        args.context.pixelStorei(args.context.UNPACK_PREMULTIPLY_ALPHA_WEBGL, 1)
        args.context.texParameteri(args.context.TEXTURE_2D, args.context.TEXTURE_MIN_FILTER, args.context.LINEAR)
        args.context.texParameteri(args.context.TEXTURE_2D, args.context.TEXTURE_MAG_FILTER, args.context.LINEAR)
        args.context.texParameteri(args.context.TEXTURE_2D, args.context.TEXTURE_WRAP_S, args.context.CLAMP_TO_EDGE)
        args.context.texParameteri(args.context.TEXTURE_2D, args.context.TEXTURE_WRAP_T, args.context.CLAMP_TO_EDGE)
        try {
          const textUploadStart = performance.now()
          args.context.texImage2D(
            args.context.TEXTURE_2D,
            0,
            args.context.RGBA,
            args.context.RGBA,
            args.context.UNSIGNED_BYTE,
            cropped as unknown as TexImageSource,
          )
          textureUploadMs += performance.now() - textUploadStart
          args.textCache.set(packet.nodeId, {
            texture,
            width: textureSourceRect.width,
            height: textureSourceRect.height,
            cacheKey: textCacheKey,
            rasterScale: textRasterScale,
          })
          const uploadedTextBytes = textureSourceRect.width * textureSourceRect.height * args.textureBytesPerPixel
          args.resourceBudget.markTextureResident(packet.nodeId, uploadedTextBytes)
          args.resourceBudget.markTextureUsed(packet.nodeId)
          textTextureUploadCount += 1
          textTextureUploadBytes += uploadedTextBytes
          totalTextureUploadBytes += uploadedTextBytes
          remainingTextTextureUploadCount = Math.max(0, remainingTextTextureUploadCount - 1)
          remainingTotalTextureUploadBytes = Math.max(0, remainingTotalTextureUploadBytes - uploadedTextBytes)
          drawCount += drawWebGLPacket(
            args.context,
            args.pipeline,
            args.effectiveFrame,
            packet.worldBounds,
            packet.color,
            packet.opacity,
            texture,
          )
          continue
        } catch {
          if (reusesCachedTexture) {
            args.textCache.delete(packet.nodeId)
            args.resourceBudget.releaseTexture(packet.nodeId)
          }
          args.context.deleteTexture(texture)
        }
      }
    }

    // Fallback: draw a solid quad when no texture is available.
    drawCount += drawWebGLPacket(
      args.context,
      args.pipeline,
      args.effectiveFrame,
      packet.worldBounds,
      packet.color,
      packet.opacity,
      null,
    )
  }

  const packetLoopMs = performance.now() - packetLoopStart
  const drawSubmitMs = Math.max(0, packetLoopMs - textureUploadMs)
  const textureUploadBudgetExceeded =
    imageTextureUploadBytes > args.textureUploadBudgetBytes ||
    imageTextureUploadCount > args.imageTextureUploadMaxCount ||
    totalTextureUploadBytes > args.textureUploadTotalBudgetBytes ||
    textTextureUploadCount > args.textTextureUploadMaxCount

  if (
    args.effectiveFrame.context.quality === 'full' &&
    args.effectiveFrame.viewport.scale >= args.highZoomTextSlaScale
  ) {
    highZoomTextSlaChecked = true
    // High-zoom text SLA fails when text remains deferred or fallback-based.
    if (interactiveTextFallbackCount > 0 || deferredTextTextureCount > 0) {
      highZoomTextSlaViolationCount = 1
    }
  }

  return {
    drawCount,
    interactiveTextFallbackCount,
    textTextureUploadCount,
    textTextureUploadBytes,
    textCacheHitCount,
    imageTextureUploadCount,
    imageTextureUploadBytes,
    imageDownsampledUploadCount,
    imageDownsampledUploadBytesSaved,
    deferredImageTextureCount,
    deferredTextTextureCount,
    totalTextureUploadBytes,
    textureUploadMs,
    drawSubmitMs,
    drawSubmitBudgetExceeded,
    textureUploadBudgetExceeded,
    highZoomTextSlaChecked,
    highZoomTextSlaViolationCount,
    cacheFallbackReason,
  }
}
