import type {CursorIntent} from '../cursor/CursorIntent.ts'
import type {InteractionTarget, TargetStack} from '../target/index.ts'
import type {OperationPhase} from '../operation/index.ts'
import type {ViewportIntent} from '../viewport/ViewportIntent.ts'
import type {InteractionRuntimeState} from './InteractionRuntimeState.ts'

/**
 * Defines command intent type emitted by interaction reducers.
 */
export type InteractionCommandType = 'preview' | 'commit' | 'cancel'

/**
 * Defines command intent payload emitted by interaction reducers.
 */
export interface InteractionCommand<TPatch = unknown> {
  /** Stores command stage intent. */
  type: InteractionCommandType
  /** Stores optional patch payload for preview/commit stages. */
  patch?: TPatch
}

/**
 * Defines warning codes emitted by runtime reducers when they safely degrade behavior.
 */
export type InteractionWarningCode =
  | 'missing-capture'
  | 'invalid-operation-phase'
  | 'unknown-tool'
  | 'invalid-target'
  | 'missing-command-bridge'
  | 'ignored-non-primary-pointer'
  | 'shortcut-blocked-by-ime'
  | 'operation-already-completed'

/**
 * Defines warning payload emitted by runtime reducers.
 */
export interface InteractionWarning {
  /** Stores stable warning code for programmatic handling. */
  code: InteractionWarningCode
  /** Stores human-readable warning message for diagnostics. */
  message: string
  /** Stores optional event type for correlation. */
  eventType?: string
}

/**
 * Defines capture intent emitted by reducers without directly mutating DOM capture.
 */
export interface CaptureIntent {
  /** Indicates whether pointer capture should be active after this event. */
  pointerCaptured: boolean
  /** Stores pointer id to capture or release. */
  pointerId?: number
  /** Stores logical capture owner label for adapter diagnostics. */
  capturedBy?: string
}

/**
 * Defines lightweight overlay intent contract emitted by reducers.
 */
export interface OverlayIntent<TPayload = unknown> {
  /** Stores overlay intent type for app adapter routing. */
  type: 'none' | 'rebuild' | 'patch'
  /** Stores optional overlay payload produced by operation/tool logic. */
  payload?: TPayload
}

/**
 * Defines debug trace payload emitted by interaction reducers.
 */
export interface InteractionTrace<TPatch = unknown> {
  /** Stores stable event id generated by adapter or runtime. */
  eventId: string
  /** Stores normalized event type label. */
  inputType: string
  /** Stores full target stack resolved for this event. */
  targetStack: InteractionTarget[]
  /** Stores selected primary target. */
  selectedTarget: InteractionTarget
  /** Stores effective tool id for this event. */
  tool: string
  /** Stores operation phase after event processing. */
  operationPhase: OperationPhase
  /** Stores command intent emitted by this event when available. */
  command?: InteractionCommand<TPatch>
  /** Stores event timestamp for sequence analysis. */
  timestamp: number
}

/**
 * Defines unified interaction result consumed by app adapters.
 */
export interface InteractionResult<TPatch = unknown, TOverlayPayload = unknown> {
  /** Stores partial runtime updates produced by this event. */
  nextState?: Partial<InteractionRuntimeState>
  /** Stores command intent for preview/commit/cancel flows. */
  command?: InteractionCommand<TPatch>
  /** Stores optional cursor intent override. */
  cursor?: CursorIntent
  /** Stores optional overlay intent output. */
  overlay?: OverlayIntent<TOverlayPayload>
  /** Stores optional pointer capture intent output. */
  capture?: CaptureIntent
  /** Stores optional viewport intent output. */
  viewport?: ViewportIntent
  /** Indicates whether adapter should call event.preventDefault(). */
  preventDefault?: boolean
  /** Indicates whether adapter should call event.stopPropagation(). */
  stopPropagation?: boolean
  /** Stores non-fatal warnings emitted during event processing. */
  warnings?: InteractionWarning[]
  /** Stores optional debug trace payload. */
  trace?: InteractionTrace<TPatch>
}

/**
 * Creates a baseline no-op interaction result for reducer defaults.
 */
export function createInteractionResult<TPatch = unknown, TOverlayPayload = unknown>(): InteractionResult<
  TPatch,
  TOverlayPayload
> {
  return {
    overlay: {type: 'none'},
    viewport: {type: 'none'},
  }
}

/**
 * Creates debug trace from resolved result and target stack snapshot.
 */
export function createInteractionTrace<TPatch = unknown>(input: {
  /** Stores event id used to correlate logs. */
  eventId: string
  /** Stores event type label. */
  inputType: string
  /** Stores target stack snapshot from resolution stage. */
  targetStack?: TargetStack
  /** Stores effective tool id after routing. */
  tool: string
  /** Stores operation phase after routing. */
  operationPhase: OperationPhase
  /** Stores command intent output when available. */
  command?: InteractionCommand<TPatch>
  /** Stores event timestamp. */
  timestamp: number
}): InteractionTrace<TPatch> {
  const targets = input.targetStack?.targets ?? [{type: 'empty'}]
  const selectedTarget = input.targetStack?.primary ?? {type: 'empty'}

  return {
    eventId: input.eventId,
    inputType: input.inputType,
    targetStack: targets,
    selectedTarget,
    tool: input.tool,
    operationPhase: input.operationPhase,
    command: input.command,
    timestamp: input.timestamp,
  }
}
