import type {TemplatePresetDefinition} from './types.ts'

export const TEMPLATE_PRESETS: TemplatePresetDefinition[] = [
  {
    id: 'demo-basic-shapes',
    label: 'Basic Shapes Demo',
    description: 'Small user-friendly layout with rectangles, ellipse, path, text, and group.',
    category: 'simple-demo',
    targetElementCount: 24,
    scale: 'tiny',
    capabilities: ['render', 'selection', 'transform', 'group'],
    interactionScenarios: ['single-select', 'multi-select', 'move', 'resize', 'rotate'],
    regression: true,
  },
  {
    id: 'demo-welcome-board',
    label: 'Welcome Board Demo',
    description: 'Poster-like starter template with mixed vector elements and labels.',
    category: 'simple-demo',
    targetElementCount: 36,
    scale: 'tiny',
    capabilities: ['render', 'text', 'mixed'],
    interactionScenarios: ['text-editing', 'selection', 'viewport-navigation'],
    regression: true,
  },
  {
    id: 'demo-wireframe',
    label: 'Wireframe Demo',
    description: 'Simple card/dashboard wireframe for quick editing walkthroughs.',
    category: 'simple-demo',
    targetElementCount: 30,
    scale: 'tiny',
    capabilities: ['render', 'group', 'selection'],
    interactionScenarios: ['group-enter', 'group-exit', 'layer-reorder'],
    regression: true,
  },
  {
    id: 'mixed-10k',
    label: 'Stress Mixed 10K',
    description: '10,000 mixed elements distributed across scene for renderer and interaction tests.',
    category: 'mixed-large',
    targetElementCount: 10000,
    scale: 'medium',
    capabilities: ['render', 'hittest', 'marquee', 'snapping', 'viewport', 'mixed'],
    interactionScenarios: ['marquee-large', 'pan-zoom-stress', 'hittest-dense'],
    performanceNotes: ['viewport culling effectiveness', 'marquee candidate count', 'pan frame time'],
    benchmark: true,
    regression: true,
  },
  {
    id: 'mixed-50k',
    label: 'Stress Mixed 50K',
    description: '50,000 mixed elements for heavy loading, culling, and manipulation tests.',
    category: 'mixed-large',
    targetElementCount: 50000,
    scale: 'large',
    capabilities: ['render', 'hittest', 'marquee', 'viewport', 'mixed'],
    interactionScenarios: ['pan-zoom-stress', 'hittest-dense', 'selection-large-batch'],
    performanceNotes: ['spatial index query time', 'render frame budget', 'initial load time'],
    benchmark: true,
  },
  {
    id: 'mixed-100k',
    label: 'Stress Mixed 100K',
    description: '100,000 mixed elements for peak-scale performance and memory pressure checks.',
    category: 'mixed-large',
    targetElementCount: 100000,
    scale: 'extreme',
    capabilities: ['render', 'viewport', 'mixed'],
    performanceNotes: ['memory pressure', 'render degradation threshold', 'spatial index build time'],
    benchmark: true,
  },
  {
    id: 'mixed-200k',
    label: 'Stress Mixed 200K',
    description: '200,000 mixed elements for extreme-scale interaction and memory stress checks.',
    category: 'mixed-large',
    targetElementCount: 200000,
    scale: 'extreme',
    capabilities: ['render', 'viewport', 'mixed', 'hittest'],
    interactionScenarios: ['pan-zoom-stress', 'selection-large-batch'],
    performanceNotes: ['peak heap usage', 'frame pacing under dense viewport', 'index update overhead'],
    benchmark: true,
  },
  {
    id: 'mixed-300k',
    label: 'Stress Mixed 300K',
    description: '300,000 mixed elements as a high-end stress profile for worst-case scene workloads.',
    category: 'mixed-large',
    targetElementCount: 300000,
    scale: 'extreme',
    capabilities: ['render', 'viewport', 'mixed'],
    interactionScenarios: ['pan-zoom-stress', 'hittest-dense'],
    performanceNotes: ['extreme scene memory pressure', 'render scheduler saturation'],
    benchmark: true,
  },
  {
    id: 'images-1k',
    label: 'Image Heavy 1K',
    description: '1,000 randomized image elements with varied sizes for image loading tests.',
    category: 'image-heavy',
    targetElementCount: 1000,
    scale: 'small',
    capabilities: ['render', 'image', 'hittest'],
    interactionScenarios: ['image-select', 'image-resize', 'viewport-zoom-image'],
    performanceNotes: ['texture upload throughput', 'image decode latency'],
    regression: true,
  },
  {
    id: 'images-10k',
    label: 'Image Heavy 10K',
    description: '10,000 randomized image elements to stress texture upload and rendering.',
    category: 'image-heavy',
    targetElementCount: 10000,
    scale: 'large',
    capabilities: ['render', 'image', 'viewport'],
    performanceNotes: ['texture memory budget', 'decode queue depth', 'cache eviction rate'],
    benchmark: true,
  },
  {
    id: 'images-50k',
    label: 'Image Heavy 50K',
    description: '50,000 image elements to stress upload throughput, decoding, and texture memory limits.',
    category: 'image-heavy',
    targetElementCount: 50000,
    scale: 'extreme',
    capabilities: ['render', 'image', 'viewport'],
    interactionScenarios: ['viewport-zoom-image', 'pan-zoom-stress'],
    performanceNotes: ['texture cache thrash threshold', 'decode backlog pressure'],
    benchmark: true,
  },

  // --- Additional test-focused presets ---

  {
    id: 'test-text-dense',
    label: 'Text Dense 500',
    description: '500 text elements with varied fonts, sizes, and rich runs for text subsystem testing.',
    category: 'simple-demo',
    targetElementCount: 500,
    scale: 'small',
    capabilities: ['render', 'text', 'hittest', 'selection'],
    interactionScenarios: ['text-select', 'text-editing', 'text-hittest'],
    performanceNotes: ['text layout cache', 'glyph atlas pressure'],
    regression: true,
  },
  {
    id: 'text-10k',
    label: 'Text Dense 10K',
    description: '10,000 text elements with varied runs for large-scale text rendering and selection testing.',
    category: 'simple-demo',
    targetElementCount: 10000,
    scale: 'large',
    capabilities: ['render', 'text', 'selection', 'hittest', 'viewport'],
    interactionScenarios: ['text-select', 'pan-zoom-stress', 'hittest-dense'],
    performanceNotes: ['glyph atlas eviction', 'text run layout throughput'],
    benchmark: true,
  },
  {
    id: 'test-deep-groups',
    label: 'Deep Groups 200',
    description: '200 elements in deeply nested groups (5+ levels) for group traversal and isolation testing.',
    category: 'simple-demo',
    targetElementCount: 200,
    scale: 'small',
    capabilities: ['render', 'group', 'selection', 'hittest'],
    interactionScenarios: ['group-enter', 'group-exit', 'nested-selection', 'isolation-mode'],
    regression: true,
  },
  {
    id: 'test-overlap-heavy',
    label: 'Overlap Heavy 1K',
    description: '1,000 heavily overlapping elements for hittest disambiguation and z-order testing.',
    category: 'simple-demo',
    targetElementCount: 1000,
    scale: 'small',
    capabilities: ['render', 'hittest', 'overlap', 'selection'],
    interactionScenarios: ['click-through', 'context-menu-overlap', 'z-order-select'],
    regression: true,
  },
  {
    id: 'test-sparse-large',
    label: 'Sparse Large 5K',
    description: '5,000 elements spread across a very large canvas for viewport culling and pan testing.',
    category: 'mixed-large',
    targetElementCount: 5000,
    scale: 'medium',
    capabilities: ['render', 'viewport', 'sparse', 'snapping'],
    interactionScenarios: ['long-distance-pan', 'zoom-to-fit', 'snap-distant'],
    performanceNotes: ['culling ratio at default zoom', 'spatial index sparsity'],
    benchmark: true,
  },
  {
    id: 'test-transform-batch',
    label: 'Transform Batch 2K',
    description: '2,000 selected elements for batch transform (move/scale/rotate) performance.',
    category: 'mixed-large',
    targetElementCount: 2000,
    scale: 'medium',
    capabilities: ['transform', 'selection', 'render'],
    interactionScenarios: ['batch-move', 'batch-scale', 'batch-rotate', 'undo-redo-batch'],
    performanceNotes: ['transform preview frame time', 'commit latency', 'undo memory'],
    benchmark: true,
    regression: true,
  },
]

export function getTemplatePresetById(id: string) {
  return TEMPLATE_PRESETS.find((preset) => preset.id === id) ?? null
}
