import type {RemoteDatasetFormat} from '../demos/remoteScenarioCatalog'

export interface PlaygroundScenarioDataManifest {
  scenarioId: string
  sourceUrl: string
  sourceLabel: string
  license: string
  checksum: string
  format: RemoteDatasetFormat
  sizeBytes: number | null
  adapterOwner: string
  fallbackPolicy: 'remote-primary-local-fallback-pending'
}

export const PLAYGROUND_SCENARIO_DATA_MANIFESTS: readonly PlaygroundScenarioDataManifest[] = [
  {scenarioId: 's1-medical-volume-slice-runtime', sourceUrl: 'https://raw.githubusercontent.com/plotly/datasets/master/volcano.csv', sourceLabel: 'Plotly volcano scalar grid', license: 'public dataset (Plotly)', checksum: '4bb4c56d182618073e8670104448c1f0fc3cf18d1eba2a9c738efba8dcc7d668', format: 'csv', sizeBytes: 11790, adapterOwner: 'playground/scenarios/S1', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's2-preop-path-simulation', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/airports.csv', sourceLabel: 'Vega airports coordinates', license: 'public dataset (Vega)', checksum: 'caeb10d97cf2946792f7f2b4e28b692c655bb6c5f0a8e048ea3625b538266dd3', format: 'csv', sizeBytes: 20774, adapterOwner: 'playground/scenarios/S2', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's3-bim-collab-review', sourceUrl: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json', sourceLabel: 'deck.gl Vancouver blocks', license: 'public dataset (deck.gl)', checksum: '05e300ba33f6fbf77a9a43748eb9a25739f228f06e2c16ed80ee78f8dc6aaf23', format: 'json', sizeBytes: 77478, adapterOwner: 'playground/scenarios/S3', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's4-cad-assembly-validation', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/cars.json', sourceLabel: 'Vega cars specifications', license: 'public dataset (Vega)', checksum: 'f686a53678b21f4231e2f6a5ba7ce5761d9d39204fccdea1caa29fb8c460e319', format: 'json', sizeBytes: 59683, adapterOwner: 'playground/scenarios/S4', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's5-gis-live-map-streaming', sourceUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson', sourceLabel: 'USGS weekly earthquakes GeoJSON', license: 'public government feed (USGS)', checksum: 'remote-content-dynamic-feed', format: 'json', sizeBytes: null, adapterOwner: 'playground/scenarios/S5', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's6-autodrive-twin-replay', sourceUrl: 'https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-elo/nbaallelo.csv', sourceLabel: 'FiveThirtyEight NBA timeline records', license: 'public dataset (FiveThirtyEight)', checksum: 'd46ed3540ee8d9eca31b3e94cc8c777e0be5156173d814ebf65b8195e8d616bc', format: 'csv', sizeBytes: 5862, adapterOwner: 'playground/scenarios/S6', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's7-city-twin-monitor-wall', sourceUrl: 'https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv', sourceLabel: 'Plotly country GDP stats', license: 'public dataset (Plotly)', checksum: '5b2311d1c6302c2b700fd1107fd0f4b550266b746fad16c22331d998c244f6ef', format: 'csv', sizeBytes: 9162, adapterOwner: 'playground/scenarios/S7', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's8-commerce-product-variant-runtime', sourceUrl: 'https://fakestoreapi.com/products', sourceLabel: 'Fake Store API product list', license: 'public demo API (FakeStore)', checksum: 'remote-content-dynamic-api', format: 'json', sizeBytes: null, adapterOwner: 'playground/scenarios/S8', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's9-molecular-volume-exploration', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/earthquakes.json', sourceLabel: 'Vega earthquake point data', license: 'public dataset (Vega)', checksum: 'a42702a83ffbae679f95d1fa53e2cae0bae13b21e599a68cdd50a44fc52129f7', format: 'json', sizeBytes: 57483, adapterOwner: 'playground/scenarios/S9', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's10-game-editor-runtime-preview', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/miserables.json', sourceLabel: 'Vega graph topology data', license: 'public dataset (Vega)', checksum: '8141048828e66a539c6915ea8c8a2eef4ba2e014e371ad614cddf37281cb88b6', format: 'json', sizeBytes: 12372, adapterOwner: 'playground/scenarios/S10', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's11-node-headless-rendering', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/unemployment-across-industries.json', sourceLabel: 'Vega unemployment time series', license: 'public dataset (Vega)', checksum: 'c12e32b5b8bf66d5ce40081a22b5557b2a8649dbdcbe03028b3df65cd66257a1', format: 'json', sizeBytes: 185641, adapterOwner: 'playground/scenarios/S11', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's12-vector-editor-optin-2d', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/seattle-weather.csv', sourceLabel: 'Vega Seattle weather records', license: 'public dataset (Vega)', checksum: '0845078a290b48e3149ab8639966824110a251db4e06fc144c06ebb534af23be', format: 'csv', sizeBytes: 48219, adapterOwner: 'playground/scenarios/S12', fallbackPolicy: 'remote-primary-local-fallback-pending'},
  {scenarioId: 's13-video-timeline-composition', sourceUrl: 'https://raw.githubusercontent.com/vega/vega-datasets/main/data/stocks.csv', sourceLabel: 'Vega stocks time series', license: 'public dataset (Vega)', checksum: 'f9953ac6693e587476b4ebf2f0b00d9bb95371ca8c39da4cc6155077b3e417cd', format: 'csv', sizeBytes: 12245, adapterOwner: 'playground/scenarios/S13', fallbackPolicy: 'remote-primary-local-fallback-pending'},
] as const
