// Runtime-facing engine facade for app shells.
//
// Keep app imports on `@vector/runtime/engine` so `@venus/engine` remains an
// implementation detail behind runtime package boundaries.
export type {
  EngineCanvasViewportState,
  EngineRenderFrame,
  EngineRenderQuality,
  EngineMarqueeApplyMode,
  EngineMarqueeBounds,
  EngineMoveSnapOptions,
  EngineMoveSnapPreview,
  EngineMarqueePoint,
  EngineMarqueeSelectableShape,
  EngineMarqueeSelectionMatchMode,
  EngineMarqueeSelectionMode,
  EngineSnapAxis,
  EngineSnapGuide,
  EngineSnapGuideLine,
  EngineMarqueeState,
  EngineSelectionHandle,
  EngineSelectionHandleBounds,
  EngineSelectionHandleKind,
  EngineSelectionHandlePoint,
  Engine,
  EngineRenderScheduler,
  EngineReplayRenderRequest,
  EngineReplayWorkerEvent,
  EngineReplayWorkerMessage,
} from '@venus/engine'

export {
  accumulateEnginePointerPanOffset,
  accumulateEngineWheelPanOffset,
  applyAffineMatrixToPoint,
  containsEngineBounds,
  buildEngineSelectionHandlesFromBounds,
  createAffineMatrixAroundPoint,
  createEngine,
  createEngineMarqueeState,
  createEngineViewportPanOrigin,
  createEngineRenderScheduler,
  createEngineReplayCoordinator,
  createCanvas2DEngineRenderer,
  doNormalizedBoundsOverlap,
  getEngineNormalizedBounds,
  getNormalizedBoundsFromBox,
  handleEngineZoomWheel,
  intersectsEngineBounds,
  isPointInsideEngineClipShape,
  isPointInsideEngineShapeHitArea,
  isPointInsideRotatedBounds,
  pickEngineSelectionHandleAtPoint,
  resetEngineZoomSession,
  resolveEngineMarqueeBounds,
  resolveEngineMarqueeSelection,
  resolveEngineMoveSnapPreview,
  resolveEngineViewportState,
  resolveNodeTransform,
  toResolvedNodeSvgTransform,
  updateEngineMarqueeState,
  zoomEngineViewportState,
} from '@venus/engine'
