import { createEngineDiagnosticsReplayFacade } from "./createEngine.diagnostics-replay.facade";
import { createEngineRuntimeFacadeNamespace } from "./createEngine.runtime.facade";
import { createEngineCapabilityFacade } from "./createEngine.capability.facade";

/**
 * Builds runtime/capability/dispose tail facade slices for createEngine return assembly.
 * @param deps Runtime and diagnostics dependencies from createEngine closure.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Dynamic facade dispatch requiring broad dependency bag
export function createEngineRuntimeCapabilityDisposeFacade(deps: any) {
  const {
    runtimeFacade,
    registerEventListener,
    unregisterEventListener,
    emitEvent,
    lastEncodedCommandCount,
    lastReplayEventCount,
    latestExecutionSnapshot,
    setDiagnosticsEnabled,
    createRuntimeReplayToken,
    replayRuntimeToken,
    resolvePublicDiagnostics,
    getDiagnosticsEnabled,
    getOverlayCount,
    captureFrame,
    getRuntimeStats,
    runtimeProfileId,
    runtimeCapabilityCount,
    lastFramePressureReason,
    lastFramePressure,
    lastFramePhase,
    lastQosDegradationLevel,
    lastQosFallbackReason,
    lastQosGuardTriggers,
    lastQosTrace,
    lastFramePressureSignals,
    lastDocumentRevision,
    lastCompileChangeSetId,
    lastCompileChangedNodeCount,
    lastExecutionDrawCount,
    lastRuntimeWorldRevision,
    lastDirtyDomainCount,
    lastReplayFirstCommandId,
    lastBoundaryViolationCount,
    lastPublicApiViolationCount,
    getBackendInfo,
    resolveRuntimeDocumentSnapshot,
    resolveRuntimeDocumentRevision,
    applyRuntimeDocumentChangeSet,
    preflightRuntimeDocumentChangeSetApply,
    compileRuntimeWorld,
    resolveRuntimeWorldSnapshotOutput,
    resolveRuntimeWorldGraphStatsOutput,
    resolveRuntimeDirtyStateOutput,
    markRuntimeDirtyDomain,
    flushRuntimeDirtyDomains,
    scheduleRuntimeIncrementalCompile,
    forceRuntimeFullCompile,
    createRuntimeFramePlan,
    inspectRuntimePlan,
    encodeRuntimeCommandPlan,
    validateRuntimeCommandBuffer,
    submitRuntimeCommandBuffer,
    submitRuntimeCommandBufferBatch,
    createRuntimeGpuResource,
    updateRuntimeGpuResource,
    destroyRuntimeGpuResource,
    createRuntimeUploadBatch,
    createRuntimeBarrierPlan,
    applyRuntimeBarrierPlan,
    readbackRuntimeResource,
    queryRuntimeViewportCandidates,
    queryRuntimeFrustumVisibleSet,
    pickGraph,
    raycastGraph,
    queryRuntimeSpatialIndex,
    switchRuntimeBackend,
    resolveRuntimeBackendFallbackHistory,
    setRuntimeBackendDebugOptions,
    captureRuntimeFrame,
    captureRuntimeCommandTrace,
    resolveRuntimePublicMetrics,
    getRuntimeTrace,
    createRuntimeDocumentSnapshot,
    validateRuntimeDocumentSnapshot,
    resolveRuntimeDocumentSchemaVersion,
    diffRuntimeDocumentSnapshots,
    rebaseRuntimeDocumentChangeSet,
    serializeRuntimeDocumentSnapshot,
    deserializeRuntimeDocumentSnapshot,
    compileRuntimeWorldFromDocument,
    queryRuntimeWorldEntity,
    queryRuntimeWorldComponent,
    queryRuntimeNodeTransform,
    formatRuntimeNodeSvgTransform,
    setRuntimeOpenWorldMap,
    getRuntimeOpenWorldMap,
    setRuntimeCollisionObstacles,
    getRuntimeCollisionObstacles,
    registerRuntimeCollider,
    unregisterRuntimeCollider,
    queryRuntimeCollisionAabb,
    evaluateRuntimeCollisionTriggers,
    setRuntimeWorldAgents,
    getRuntimeWorldAgents,
    registerRuntimeNavigationPath,
    unregisterRuntimeNavigationPath,
    getRuntimeNavigationPaths,
    stepRuntimeWorldAgents,
    stepRuntimeNavigationPathAgents,
    resolveRuntimeWorldCollision,
    clearRuntimeWorldSnapshot,
    createRuntimeAuthoringGraphSnapshot,
    compareRuntimeAuthoringGraphSnapshots,
    createRuntimeAuthoringPreviewToken,
    resolveRuntimeAuthoringDiagnostics,
    markRuntimeDirtyDomainsBatch,
    resolveRuntimePendingDirtyDomains,
    resetRuntimeDirtyState,
    createRuntimeCommandEncoder,
    optimizeRuntimeCommandBuffer,
    inspectRuntimeCommandBuffer,
    replayRuntimeCommandBuffer,
    resolveRuntimeBackendListAvailableOutput,
    selectRuntimeBackend,
    resolveRuntimeBackendGetActiveOutput,
    resolveRuntimeBackendCapabilities,
    resolveRuntimeBackendLimits,
    resolveRuntimeBackendGetFallbackTraceOutput,
    probeRuntimeHeadlessBackend,
    createRuntimeVisibilityPlan,
    createRuntimeLodPlan,
    createRuntimeRoiPlan,
    createRuntimeBudgetPlan,
    createRuntimeHitGeometryPayload,
    resolveRuntimeHitTolerance,
    requestRuntimePlanFrame,
    cancelRuntimePlanFrame,
    setRuntimePlanInteractiveInterval,
    resolveRuntimePlanSchedulerDiagnostics,
    setRuntimeLightingCollection,
    getRuntimeLightingCollection,
    clearRuntimeLightingCollection,
    applyRuntimeLightingProfile,
    resolveRuntimeLightingEnvironment,
    applyRuntimeLightingEnvironment,
    registerRuntimeModelAsset,
    unregisterRuntimeModelAsset,
    setRuntimeModelInstances,
    getRuntimeModelInstances,
    resolveRuntimeModelDiagnostics,
    registerRuntimeResource,
    updateRuntimeResource,
    releaseRuntimeResource,
    pinRuntimeResource,
    unpinRuntimeResource,
    getRuntimeResourceResidency,
    collectRuntimeResources,
    startRuntimeTrace,
    stopRuntimeTrace,
    getRuntimeMetricsSnapshot,
    queryGraph,
    resolvePublicDiagnosticsForCapability,
    disposeRuntimePlanScheduler,
    isMounted,
  } = deps;

  return {
      /** Keeps headless render parity by reusing the primary render path output counters. */
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Headless delegate forwarding to dynamic render
      async renderHeadless(this: any) {
      const rendered = await this.render();
      return { drawCount: rendered.drawCount, visibleCount: rendered.visibleCount };
    },
    /**
     * Preserves legacy event registration API by delegating to engine.events.on.
     * @param event Event type token.
     * @param listener Event listener callback.
     */
    on(event: string, listener: (payload: unknown) => void) {
      registerEventListener(event, listener);
    },
    /**
     * Preserves legacy event unregister API by delegating to engine.events.off.
     * @param event Event type token.
     * @param listener Event listener callback.
     */
    off(event: string, listener: (payload: unknown) => void) {
      unregisterEventListener(event, listener);
    },
    /**
     * Preserves legacy one-shot listener API by delegating to engine.events.once.
     * @param event Event type token.
     * @param listener Event listener callback.
       */
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Legacy once API forwarding to dynamic this.events
      once(this: any, event: string, listener: (payload: unknown) => void) {
      this.events.once(event, listener);
    },
    ...createEngineDiagnosticsReplayFacade({
        resolveMetrics: () => ({
          encodedCommandCount: lastEncodedCommandCount,
          replayedCommandCount: lastReplayEventCount,
          drawCount: latestExecutionSnapshot.drawCount,
        }),
      setDiagnosticsEnabledFlag: (enabled: boolean) => { setDiagnosticsEnabled(enabled); },
      emitEvent,
      captureDebugFrameOutput: () => ({ mimeType: "image/png", dataUrl: "data:image/png;base64," }),
      createRuntimeReplayToken,
      replayRuntimeToken,
      resolvePublicDiagnostics,
      isDiagnosticsEnabled: () => getDiagnosticsEnabled(),
      getOverlayCount: () => getOverlayCount(),
      captureFrame,
      resolveStats: () => ({
        ...getRuntimeStats(),
        runtimeProfileId,
        runtimeCapabilityCount,
        lastFramePressureReason,
        lastFramePressure,
        lastFramePhase,
        lastQosDegradationLevel,
        lastQosFallbackReason,
        lastQosGuardTriggers,
        lastQosTrace,
        lastFramePressureSignals,
        lastDocumentRevision,
        lastCompileChangeSetId,
        lastCompileChangedNodeCount,
        lastExecutionDrawCount,
        lastRuntimeWorldRevision,
        lastDirtyDomainCount,
        lastEncodedCommandCount,
        lastReplayEventCount,
        lastReplayFirstCommandId,
        lastBoundaryViolationCount,
        lastPublicApiViolationCount,
      }),
      getBackendInfo,
    }),
    runtime: createEngineRuntimeFacadeNamespace({
        resolveRuntimeDocumentSnapshot,
        resolveRuntimeDocumentRevision,
        applyRuntimeDocumentChangeSet,
        preflightRuntimeDocumentChangeSetApply,
        compileRuntimeWorld,
        resolveRuntimeWorldSnapshotOutput,
        resolveRuntimeWorldGraphStatsOutput,
        resolveRuntimeDirtyStateOutput,
        markRuntimeDirtyDomain,
        flushRuntimeDirtyDomains,
        scheduleRuntimeIncrementalCompile,
        forceRuntimeFullCompile,
        createRuntimeFramePlan,
        inspectRuntimePlan,
        encodeRuntimeCommandPlan,
        validateRuntimeCommandBuffer,
        submitRuntimeCommandBuffer,
        submitRuntimeCommandBufferBatch,
        createRuntimeGpuResource,
        updateRuntimeGpuResource,
        destroyRuntimeGpuResource,
        createRuntimeUploadBatch,
        createRuntimeBarrierPlan,
        applyRuntimeBarrierPlan,
        readbackRuntimeResource,
        queryRuntimeViewportCandidates,
        queryRuntimeFrustumVisibleSet,
        pickGraph,
        raycastGraph,
        queryRuntimeSpatialIndex,
      resolveRuntimeBackendState: () => {
        const backendInfo = getBackendInfo();
        return {
          requested: backendInfo.requested,
          resolved: backendInfo.resolved,
          fallbackReason: backendInfo.fallbackReason,
        };
      },
        switchRuntimeBackend,
        resolveRuntimeBackendFallbackHistory,
        setRuntimeBackendDebugOptions,
        captureRuntimeFrame,
        captureRuntimeCommandTrace,
        createRuntimeReplayToken,
        replayRuntimeToken,
        resolveRuntimePublicMetrics,
        getRuntimeTrace,
        createRuntimeDocumentSnapshot,
        validateRuntimeDocumentSnapshot,
        resolveRuntimeDocumentSchemaVersion,
        diffRuntimeDocumentSnapshots,
        rebaseRuntimeDocumentChangeSet,
        serializeRuntimeDocumentSnapshot,
        deserializeRuntimeDocumentSnapshot,
        compileRuntimeWorldFromDocument,
        queryRuntimeWorldEntity,
        queryRuntimeWorldComponent,
        queryRuntimeNodeTransform,
        formatRuntimeNodeSvgTransform,
        setRuntimeOpenWorldMap,
        getRuntimeOpenWorldMap,
        setRuntimeCollisionObstacles,
        getRuntimeCollisionObstacles,
        registerRuntimeCollider,
        unregisterRuntimeCollider,
        queryRuntimeCollisionAabb,
        evaluateRuntimeCollisionTriggers,
        setRuntimeWorldAgents,
        getRuntimeWorldAgents,
        registerRuntimeNavigationPath,
        unregisterRuntimeNavigationPath,
        getRuntimeNavigationPaths,
        stepRuntimeWorldAgents,
        stepRuntimeNavigationPathAgents,
        resolveRuntimeWorldCollision,
        clearRuntimeWorldSnapshot,
        createRuntimeAuthoringGraphSnapshot,
        compareRuntimeAuthoringGraphSnapshots,
        createRuntimeAuthoringPreviewToken,
        resolveRuntimeAuthoringDiagnostics,
        markRuntimeDirtyDomainsBatch,
        resolveRuntimePendingDirtyDomains,
        resetRuntimeDirtyState,
        createRuntimeCommandEncoder,
        optimizeRuntimeCommandBuffer,
        inspectRuntimeCommandBuffer,
        replayRuntimeCommandBuffer,
        resolveRuntimeBackendListAvailableOutput,
        selectRuntimeBackend,
        resolveRuntimeBackendGetActiveOutput,
        resolveRuntimeBackendCapabilities,
        resolveRuntimeBackendLimits,
        resolveRuntimeBackendGetFallbackTraceOutput,
        probeRuntimeHeadlessBackend,
        createRuntimeVisibilityPlan,
        createRuntimeLodPlan,
        createRuntimeRoiPlan,
        createRuntimeBudgetPlan,
        createRuntimeHitGeometryPayload,
        resolveRuntimeHitTolerance,
        requestRuntimePlanFrame,
        cancelRuntimePlanFrame,
        setRuntimePlanInteractiveInterval,
      resolveRuntimePlanSchedulerDiagnostics,
        setRuntimeLightingCollection,
        getRuntimeLightingCollection,
        clearRuntimeLightingCollection,
        applyRuntimeLightingProfile,
        resolveRuntimeLightingEnvironment,
        applyRuntimeLightingEnvironment,
        registerRuntimeModelAsset,
        unregisterRuntimeModelAsset,
        setRuntimeModelInstances,
        getRuntimeModelInstances,
        resolveRuntimeModelDiagnostics,
        registerRuntimeResource,
        updateRuntimeResource,
        releaseRuntimeResource,
        pinRuntimeResource,
        unpinRuntimeResource,
        getRuntimeResourceResidency,
        collectRuntimeResources,
        startRuntimeTrace,
        stopRuntimeTrace,
        getRuntimeMetricsSnapshot,
    }),
    capability: createEngineCapabilityFacade({
        queryRuntimeNodeTransform,
        formatRuntimeNodeSvgTransform,
        queryGraph,
        createRuntimeHitGeometryPayload,
        pickGraph,
        raycastGraph,
        resolveRuntimeHitTolerance,
        resolvePublicDiagnostics: resolvePublicDiagnosticsForCapability,
      createRuntimeReplayToken, replayRuntimeToken,
    }),
    /** Disposes runtime resources and emits lifecycle-disposed event payload. */
    dispose() {
      disposeRuntimePlanScheduler();
      runtimeFacade.dispose();
      emitEvent("engine.lifecycle.disposed", {
        mounted: isMounted(),
      });
    },
  };
}
