import type {EditorFileDocument} from '../../types/index.ts'

export const MOCK_FILE_TRAILING_ELEMENTS: EditorFileDocument['elements'] = [
  {
    id: 'fixture-full-coverage-element',
    type: 'path',
    layer: 999,
    name: 'Full Coverage Element',
    show: true,
    x: 24,
    y: 24,
    cx: 120,
    cy: 120,
    r1: 48,
    r2: 24,
    width: 192,
    height: 96,
    rotation: 15,
    flipX: false,
    flipY: true,
    points: [
      {x: 24, y: 24},
      {x: 216, y: 24},
      {x: 216, y: 120},
      {x: 24, y: 120},
      {x: 24, y: 24},
    ],
    bezierPoints: [
      {
        anchor: {x: 24, y: 24},
        cp1: {x: 48, y: 12},
        cp2: {x: 72, y: 36},
      },
      {
        anchor: {x: 216, y: 120},
        cp1: {x: 192, y: 132},
        cp2: {x: 168, y: 108},
      },
    ],
    opacity: 0.88,
    fill: {
      enabled: true,
      color: '#f8fafc',
      gradient: {
        type: 'diamond',
        centerX: 0.5,
        centerY: 0.5,
        radius: 0.8,
        stops: [
          {offset: 0, color: '#e2e8f0', opacity: 0.9},
          {offset: 1, color: '#cbd5e1', opacity: 0.7},
        ],
      },
    },
    stroke: {
      enabled: true,
      color: '#334155',
      weight: 3,
      cap: 'round',
      join: 'bevel',
      dashed: true,
      gradient: {
        type: 'linear',
        angle: 30,
        stops: [
          {offset: 0, color: '#0f172a'},
          {offset: 1, color: '#475569'},
        ],
      },
    },
    shadow: {
      enabled: true,
      color: 'rgba(15, 23, 42, 0.3)',
      offsetX: 4,
      offsetY: 6,
      blur: 10,
    },
    cornerRadius: 8,
    cornerRadii: {
      topLeft: 8,
      topRight: 12,
      bottomRight: 16,
      bottomLeft: 10,
    },
    ellipseStartAngle: 25,
    ellipseEndAngle: 320,
    asset: 'mock-image-asset-hero',
    assetUrl: 'blob:mock-file-coverage',
    clipPathId: 'clip-hole-shape',
    clipRule: 'evenodd',
    maskGroupId: 'mask-group-fixture',
    maskRole: 'host',
    fillStyleId: 'fill-primary',
    strokeStyleId: 'stroke-primary',
    textStyleId: 'text-primary',
    effectStyleId: 'effect-primary',
    extensions: {
      fixtureRole: 'full-coverage',
      version: 1,
    },
    parentId: null,
    childIds: [],
    text: 'Coverage text payload',
    textRuns: [
      {
        start: 0,
        end: 8,
        style: {
          color: '#0f172a',
          fontFamily: 'Inter, sans-serif',
          fontSize: 14,
          fontWeight: 600,
          letterSpacing: 0.2,
          lineHeight: 20,
          textAlign: 'left',
          verticalAlign: 'top',
          paragraphIndentLeft: 4,
          paragraphIndentFirst: 8,
          paragraphIndentRight: 6,
          paragraphSpaceBeforeLine: 2,
          paragraphSpaceAfterLine: 3,
          shadow: {
            color: 'rgba(15, 23, 42, 0.2)',
            offsetX: 1,
            offsetY: 1,
            blur: 2,
          },
        },
      },
    ],
  },
  {
    id: 'sticker-tag',
    type: 'polygon',
    name: 'Sticker Tag',
    x: 416,
    y: 196,
    width: 150,
    height: 112,
    parentId: null,
    points: [
      {x: 452, y: 196},
      {x: 566, y: 218},
      {x: 548, y: 292},
      {x: 426, y: 308},
      {x: 416, y: 244},
    ],
    fill: {
      enabled: true,
      color: '#ede9fe',
      gradient: {
        type: 'radial',
        centerX: 0.4,
        centerY: 0.35,
        radius: 0.85,
        stops: [
          {offset: 0, color: '#f5f3ff'},
          {offset: 1, color: '#ddd6fe'},
        ],
      },
    },
    stroke: {enabled: true, color: '#6d28d9', weight: 2},
    shadow: {
      enabled: true,
      color: 'rgba(76, 29, 149, 0.28)',
      offsetX: 0,
      offsetY: 8,
      blur: 12,
    },
  },
  {
    id: 'clip-hole-shape',
    type: 'path',
    name: 'Clip Hole Shape',
    x: 782,
    y: 66,
    width: 128,
    height: 88,
    parentId: null,
    points: [
      {x: 782, y: 66},
      {x: 910, y: 66},
      {x: 910, y: 154},
      {x: 782, y: 154},
      {x: 782, y: 66},
    ],
    fill: {enabled: true, color: '#e2e8f0'},
    stroke: {enabled: true, color: '#64748b', weight: 1},
  },
  {
    id: 'clip-hole-image',
    type: 'image',
    name: 'Clip EvenOdd Image',
    x: 772,
    y: 58,
    width: 148,
    height: 108,
    parentId: null,
    asset: 'mock-image-asset-accent',
    opacity: 1,
    clipPathId: 'clip-hole-shape',
    clipRule: 'evenodd',
    fill: {enabled: false, color: '#ffffff'},
    stroke: {enabled: false, color: '#111827', weight: 0},
  },
]
