import type {EditorFileDocument} from '../../types/index.ts'
import {
  createAccentImageDataUrl,
  createHeroImageDataUrl,
  createStarPoints,
  ribbonPath,
} from './mockFile.images.ts'
import {MOCK_FILE_TRAILING_ELEMENTS} from './mockFile.trailingElements.ts'

export const MOCK_FILE: EditorFileDocument = {
  id: 'mock-file',
  name: 'Untitled',
  version: '0.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  schema: {
    name: 'venus.vector-editor',
    version: 1,
    major: 1,
    minor: 0,
  },
  pages: [
    {
      id: 'page-main',
      name: 'Main Page',
      width: 960,
      height: 640,
    },
  ],
  activePageId: 'page-main',
  lifecycle: {
    state: 'opened',
    dirty: false,
    lastSavedAt: Date.now(),
    recoveryReason: 'mock-seed',
    lastTransitionSource: {
      kind: 'system',
      event: 'mock.seed',
      issuedAt: Date.now(),
    },
    lastDirtySource: {
      commandType: 'mock.seed',
      commandId: 'mock-seed-command',
      transactionId: 'mock-seed-transaction',
      issuedAt: Date.now(),
    },
  },
  styleReferences: {
    fills: {'fill-primary': {name: 'Primary Fill'}},
    strokes: {'stroke-primary': {name: 'Primary Stroke'}},
    texts: {'text-primary': {name: 'Primary Text'}},
    effects: {'effect-primary': {name: 'Primary Effect'}},
  },
  extensions: {
    fixture: true,
    source: 'mock-file',
  },
  config: {
    page: {
      unit: 'px',
      width: 960,
      height: 640,
      dpi: 72,
    },
    editor: {
      readOnly: false,
      migrationDiagnostics: [
        {
          code: 'migration.payload.invalid',
          phase: 'normalize',
          message: 'Mock diagnostic for contract coverage.',
          severity: 'warning',
          details: {origin: 'mock-file'},
        },
      ],
      crashRecoveryReplay: {
        maxEntries: 20,
        localOnly: {
          mode: 'local-only',
          entries: [
            {
              id: 'replay-local-1',
              label: 'Seed Local Replay',
              source: 'local',
              forward: [{op: 'add'}],
              backward: [{op: 'remove'}],
              transactionId: 'transaction-local-1',
              issuedAt: Date.now(),
            },
          ],
        },
        merged: {
          mode: 'merged',
          entries: [
            {
              id: 'replay-merged-1',
              label: 'Seed Merged Replay',
              source: 'remote',
              forward: [{op: 'replace'}],
              backward: [{op: 'replace'}],
              transactionId: 'transaction-merged-1',
              issuedAt: Date.now(),
            },
          ],
        },
      },
      crashRecoveryReplayMode: 'merged',
    },
  },
  elements: [
    {
      id: 'group-cards',
      type: 'group',
      name: 'Feature Cards',
      x: 58,
      y: 94,
      width: 304,
      height: 248,
      parentId: null,
      childIds: ['card-analytics', 'card-workflow', 'card-badge'],
    },
    {
      id: 'card-analytics',
      type: 'rectangle',
      name: 'Analytics Card',
      x: 72,
      y: 114,
      width: 180,
      height: 104,
      parentId: 'group-cards',
      fill: {
        enabled: true,
        color: '#eff6ff',
        gradient: {
          type: 'linear',
          angle: 125,
          stops: [
            {offset: 0, color: '#dbeafe'},
            {offset: 1, color: '#eff6ff'},
          ],
        },
      },
      stroke: {
        enabled: true,
        color: '#1d4ed8',
        weight: 2,
        gradient: {
          type: 'linear',
          angle: 90,
          stops: [
            {offset: 0, color: '#2563eb'},
            {offset: 1, color: '#1d4ed8'},
          ],
        },
      },
      shadow: {
        enabled: true,
        color: 'rgba(37, 99, 235, 0.22)',
        offsetX: 0,
        offsetY: 6,
        blur: 14,
      },
      cornerRadius: 16,
    },
    {
      id: 'card-workflow',
      type: 'rectangle',
      name: 'Workflow Card',
      x: 196,
      y: 196,
      width: 148,
      height: 118,
      parentId: 'group-cards',
      fill: {enabled: true, color: '#fff7ed'},
      stroke: {enabled: true, color: '#c2410c', weight: 2},
      cornerRadii: {
        topLeft: 24,
        topRight: 8,
        bottomRight: 24,
        bottomLeft: 8,
      },
    },
    {
      id: 'card-badge',
      type: 'star',
      name: 'Feature Badge',
      x: 278,
      y: 98,
      width: 72,
      height: 72,
      parentId: 'group-cards',
      points: createStarPoints(278, 98, 72, 72),
      fill: {enabled: true, color: '#fde68a'},
      stroke: {enabled: true, color: '#a16207', weight: 2},
    },
    {
      id: 'title-main',
      type: 'text',
      name: 'Main Title',
      text: 'Venus Workspace',
      textRuns: [
        {
          start: 0,
          end: 5,
          style: {
            color: '#0f172a',
            fontFamily: 'Inter, sans-serif',
            fontSize: 42,
            fontWeight: 700,
            lineHeight: 48,
            letterSpacing: -0.3,
            shadow: {
              color: 'rgba(2, 132, 199, 0.18)',
              offsetX: 0,
              offsetY: 2,
              blur: 4,
            },
          },
        },
        {
          start: 5,
          end: 15,
          style: {
            color: '#0369a1',
            fontFamily: 'Inter, sans-serif',
            fontSize: 42,
            fontWeight: 800,
            lineHeight: 48,
            letterSpacing: -0.3,
          },
        },
      ],
      x: 420,
      y: 52,
      width: 370,
      height: 52,
      parentId: null,
      fill: {enabled: true, color: '#0f172a'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    {
      id: 'title-sub',
      type: 'text',
      name: 'Sub Title',
      text: 'Clean baseline scene for alignment, clipping, and path edits',
      textRuns: [
        {
          start: 0,
          end: 20,
          style: {
            color: '#0f766e',
            fontFamily: 'Inter, sans-serif',
            fontSize: 18,
            fontWeight: 600,
            lineHeight: 24,
          },
        },
        {
          start: 20,
          end: 58,
          style: {
            color: '#0f172a',
            fontFamily: 'Inter, sans-serif',
            fontSize: 18,
            fontWeight: 400,
            lineHeight: 24,
          },
        },
      ],
      x: 420,
      y: 104,
      width: 460,
      height: 40,
      parentId: null,
      fill: {enabled: true, color: '#0f766e'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    {
      id: 'text-multiline-style-demo',
      type: 'text',
      name: 'Multiline Style Demo',
      text: 'Line One: Display\nLine Two: Emphasis\nLine Three: Notes',
      textRuns: [
        {
          start: 0,
          end: 17,
          style: {
            color: '#0f172a',
            fontFamily: 'Inter, sans-serif',
            fontSize: 28,
            fontWeight: 700,
            lineHeight: 34,
            letterSpacing: -0.2,
          },
        },
        {
          start: 18,
          end: 36,
          style: {
            color: '#be123c',
            fontFamily: 'Inter, sans-serif',
            fontSize: 22,
            fontWeight: 600,
            lineHeight: 30,
            letterSpacing: 0.1,
          },
        },
        {
          start: 37,
          end: 54,
          style: {
            color: '#334155',
            fontFamily: 'Inter, sans-serif',
            fontSize: 18,
            fontWeight: 400,
            lineHeight: 26,
            letterSpacing: 0.2,
          },
        },
      ],
      x: 420,
      y: 146,
      width: 330,
      height: 104,
      parentId: null,
      fill: {enabled: true, color: '#0f172a'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    {
      id: 'shape-circle-demo',
      type: 'ellipse',
      name: 'Circle Demo',
      x: 772,
      y: 188,
      width: 76,
      height: 76,
      parentId: null,
      fill: {
        enabled: true,
        color: '#fde68a',
        gradient: {
          type: 'radial',
          centerX: 0.45,
          centerY: 0.35,
          radius: 0.8,
          stops: [
            {offset: 0, color: '#fef9c3'},
            {offset: 1, color: '#f59e0b'},
          ],
        },
      },
      stroke: {enabled: true, color: '#a16207', weight: 2},
      shadow: {
        enabled: true,
        color: 'rgba(161, 98, 7, 0.28)',
        offsetX: 0,
        offsetY: 6,
        blur: 10,
      },
    },
    {
      id: 'shape-ellipse-arc-demo',
      type: 'ellipse',
      name: 'Ellipse Arc Demo',
      x: 860,
      y: 190,
      width: 96,
      height: 96,
      parentId: null,
      ellipseStartAngle: 40,
      ellipseEndAngle: 310,
      fill: {
        enabled: true,
        color: '#dbeafe',
      },
      stroke: {enabled: true, color: '#1d4ed8', weight: 2},
      shadow: {
        enabled: true,
        color: 'rgba(29, 78, 216, 0.22)',
        offsetX: 0,
        offsetY: 4,
        blur: 8,
      },
    },
    {
      id: 'group-roadmap',
      type: 'group',
      name: 'Roadmap Group',
      x: 392,
      y: 334,
      width: 184,
      height: 196,
      parentId: null,
      childIds: ['roadmap-panel', 'roadmap-milestone-a', 'roadmap-milestone-b', 'roadmap-link'],
    },
    {
      id: 'roadmap-panel',
      type: 'rectangle',
      name: 'Roadmap Panel',
      x: 404,
      y: 348,
      width: 162,
      height: 170,
      parentId: 'group-roadmap',
      fill: {enabled: true, color: '#f1f5f9'},
      stroke: {enabled: true, color: '#334155', weight: 2},
      cornerRadius: 18,
    },
    {
      id: 'roadmap-milestone-a',
      type: 'ellipse',
      name: 'Milestone A',
      x: 430,
      y: 378,
      width: 26,
      height: 26,
      parentId: 'group-roadmap',
      fill: {enabled: true, color: '#22c55e'},
      stroke: {enabled: true, color: '#166534', weight: 2},
    },
    {
      id: 'roadmap-milestone-b',
      type: 'ellipse',
      name: 'Milestone B',
      x: 510,
      y: 450,
      width: 30,
      height: 30,
      parentId: 'group-roadmap',
      fill: {enabled: true, color: '#f59e0b'},
      stroke: {enabled: true, color: '#92400e', weight: 2},
    },
    {
      id: 'roadmap-link',
      type: 'lineSegment',
      name: 'Roadmap Connector',
      x: 442,
      y: 392,
      width: 84,
      height: 74,
      parentId: 'group-roadmap',
      points: [
        {x: 442, y: 392},
        {x: 526, y: 466},
      ],
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: true, color: '#0f172a', weight: 3},
    },
    {
      id: 'roadmap-caption',
      type: 'text',
      name: 'Roadmap Caption',
      text: 'A/B milestones + connector for line and group transform checks',
      x: 392,
      y: 536,
      width: 280,
      height: 36,
      parentId: null,
      fill: {enabled: true, color: '#334155'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    {
      id: 'mask-pentagon',
      type: 'polygon',
      name: 'Mask Pentagon',
      x: 594,
      y: 176,
      width: 292,
      height: 218,
      parentId: null,
      points: [
        {x: 676, y: 176},
        {x: 866, y: 220},
        {x: 848, y: 366},
        {x: 648, y: 394},
        {x: 594, y: 276},
      ],
      fill: {enabled: true, color: '#f8fafc'},
      stroke: {enabled: true, color: '#94a3b8', weight: 1},
    },
    {
      id: 'hero-image',
      type: 'image',
      name: 'Hero Image',
      x: 566,
      y: 162,
      width: 332,
      height: 238,
      parentId: null,
      asset: 'mock-image-asset-hero',
      opacity: 1,
      clipPathId: 'mask-pentagon',
      clipRule: 'nonzero',
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    {
      id: 'line-check',
      type: 'lineSegment',
      name: 'Line Position Check',
      x: 120,
      y: 420,
      width: 160,
      height: 120,
      parentId: null,
      points: [
        {x: 280, y: 420},
        {x: 120, y: 540},
      ],
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: true, color: '#dc2626', weight: 4},
      rotation: 0,
    },
    {
      id: 'path-ribbon',
      type: 'path',
      name: 'Ribbon Path',
      x: ribbonPath.bounds.x,
      y: ribbonPath.bounds.y,
      width: ribbonPath.bounds.width,
      height: ribbonPath.bounds.height,
      parentId: null,
      points: ribbonPath.points,
      bezierPoints: ribbonPath.bezierPoints,
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: true, color: '#0f766e', weight: 3},
    },
    {
      id: 'path-polyline',
      type: 'path',
      name: 'Polyline Accent',
      x: 676,
      y: 456,
      width: 212,
      height: 130,
      parentId: null,
      points: [
        {x: 676, y: 456},
        {x: 724, y: 502},
        {x: 784, y: 472},
        {x: 842, y: 548},
        {x: 888, y: 496},
      ],
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: true, color: '#1d4ed8', weight: 2},
    },
    {
      id: 'accent-image',
      type: 'image',
      name: 'Accent Image',
      x: 38,
      y: 402,
      width: 216,
      height: 140,
      parentId: null,
      asset: 'mock-image-asset-accent',
      opacity: 1,
      fill: {enabled: false, color: '#ffffff'},
      stroke: {enabled: false, color: '#111827', weight: 0},
    },
    ...MOCK_FILE_TRAILING_ELEMENTS,
  ],
  assets: [
    {
      id: 'mock-image-asset-hero',
      name: 'Hero Asset',
      type: 'image',
      mimeType: 'image/svg+xml',
      file: undefined,
      imageRef: {kind: 'mock-image-ref'},
      objectUrl: createHeroImageDataUrl(),
    },
    {
      id: 'mock-image-asset-accent',
      name: 'Accent Asset',
      type: 'image',
      mimeType: 'image/svg+xml',
      objectUrl: createAccentImageDataUrl(),
    },
  ],
}
