import type {EditorFileDocument} from '../../types/index.ts'

export const MOCK_FILE_TRAILING_ELEMENTS: EditorFileDocument['elements'] = [
  {
    id: 'sticker-tag',
    type: 'polygon',
    name: 'Sticker Tag',
    x: 416,
    y: 196,
    width: 150,
    height: 112,
    parentId: null,
    points: [
      {x: 452, y: 196},
      {x: 566, y: 218},
      {x: 548, y: 292},
      {x: 426, y: 308},
      {x: 416, y: 244},
    ],
    fill: {
      enabled: true,
      color: '#ede9fe',
      gradient: {
        type: 'radial',
        centerX: 0.4,
        centerY: 0.35,
        radius: 0.85,
        stops: [
          {offset: 0, color: '#f5f3ff'},
          {offset: 1, color: '#ddd6fe'},
        ],
      },
    },
    stroke: {enabled: true, color: '#6d28d9', weight: 2},
    shadow: {
      enabled: true,
      color: 'rgba(76, 29, 149, 0.28)',
      offsetX: 0,
      offsetY: 8,
      blur: 12,
    },
  },
  {
    id: 'clip-hole-shape',
    type: 'path',
    name: 'Clip Hole Shape',
    x: 782,
    y: 66,
    width: 128,
    height: 88,
    parentId: null,
    points: [
      {x: 782, y: 66},
      {x: 910, y: 66},
      {x: 910, y: 154},
      {x: 782, y: 154},
      {x: 782, y: 66},
    ],
    fill: {enabled: true, color: '#e2e8f0'},
    stroke: {enabled: true, color: '#64748b', weight: 1},
  },
  {
    id: 'clip-hole-image',
    type: 'image',
    name: 'Clip EvenOdd Image',
    x: 772,
    y: 58,
    width: 148,
    height: 108,
    parentId: null,
    asset: 'mock-image-asset-accent',
    opacity: 1,
    clipPathId: 'clip-hole-shape',
    clipRule: 'evenodd',
    fill: {enabled: false, color: '#ffffff'},
    stroke: {enabled: false, color: '#111827', weight: 0},
  },
]
