// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Arc {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Arc {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArc(bb:flatbuffers.ByteBuffer, obj?:Arc):Arc {
  return (obj || new Arc()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArc(bb:flatbuffers.ByteBuffer, obj?:Arc):Arc {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Arc()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

startAngle():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

sweepAngle():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

useCenter():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "EditorData.Arc" {
  return 'EditorData.Arc';
}

static startArc(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(0, radius, 0.0);
}

static addStartAngle(builder:flatbuffers.Builder, startAngle:number) {
  builder.addFieldFloat32(1, startAngle, 0.0);
}

static addSweepAngle(builder:flatbuffers.Builder, sweepAngle:number) {
  builder.addFieldFloat32(2, sweepAngle, 0.0);
}

static addUseCenter(builder:flatbuffers.Builder, useCenter:boolean) {
  builder.addFieldInt8(3, +useCenter, +false);
}

static endArc(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createArc(builder:flatbuffers.Builder, radius:number, startAngle:number, sweepAngle:number, useCenter:boolean):flatbuffers.Offset {
  Arc.startArc(builder);
  Arc.addRadius(builder, radius);
  Arc.addStartAngle(builder, startAngle);
  Arc.addSweepAngle(builder, sweepAngle);
  Arc.addUseCenter(builder, useCenter);
  return Arc.endArc(builder);
}
}
