// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum BooleanOp {
  None = 0,
  Union = 1,
  Difference = 2,
  Intersect = 3,
  Xor = 4
}
