// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Circle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Circle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCircle(bb:flatbuffers.ByteBuffer, obj?:Circle):Circle {
  return (obj || new Circle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCircle(bb:flatbuffers.ByteBuffer, obj?:Circle):Circle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Circle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static getFullyQualifiedName(): "EditorData.Circle" {
  return 'EditorData.Circle';
}

static startCircle(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(0, radius, 0.0);
}

static endCircle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCircle(builder:flatbuffers.Builder, radius:number):flatbuffers.Offset {
  Circle.startCircle(builder);
  Circle.addRadius(builder, radius);
  return Circle.endCircle(builder);
}
}
