// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BooleanOp } from '../editor-data/boolean-op.js';
import { ColorRGBA } from '../editor-data/color-rgba.js';
import { EntityData, unionToEntityData, unionListToEntityData } from '../editor-data/entity-data.js';
import { FillData, unionToFillData, unionListToFillData } from '../editor-data/fill-data.js';
import { Matrix3x3 } from '../editor-data/matrix3x3.js';


export class Element {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Element {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsElement(bb:flatbuffers.ByteBuffer, obj?:Element):Element {
  return (obj || new Element()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsElement(bb:flatbuffers.ByteBuffer, obj?:Element):Element {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Element()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

transform(obj?:Matrix3x3):Matrix3x3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Matrix3x3()).__init(this.bb_pos + offset, this.bb!) : null;
}

fillType():FillData {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FillData.NONE;
}

fill<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

strokeColor(obj?:ColorRGBA):ColorRGBA|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ColorRGBA()).__init(this.bb_pos + offset, this.bb!) : null;
}

strokeWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

isVisible():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

booleanOp():BooleanOp {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : BooleanOp.None;
}

dataType():EntityData {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : EntityData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static getFullyQualifiedName(): "EditorData.Element" {
  return 'EditorData.Element';
}

static startElement(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addTransform(builder:flatbuffers.Builder, transformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, transformOffset, 0);
}

static addFillType(builder:flatbuffers.Builder, fillType:FillData) {
  builder.addFieldInt8(3, fillType, FillData.NONE);
}

static addFill(builder:flatbuffers.Builder, fillOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, fillOffset, 0);
}

static addStrokeColor(builder:flatbuffers.Builder, strokeColorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, strokeColorOffset, 0);
}

static addStrokeWidth(builder:flatbuffers.Builder, strokeWidth:number) {
  builder.addFieldFloat32(6, strokeWidth, 0.0);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(7, opacity, 0.0);
}

static addIsVisible(builder:flatbuffers.Builder, isVisible:boolean) {
  builder.addFieldInt8(8, +isVisible, +true);
}

static addBooleanOp(builder:flatbuffers.Builder, booleanOp:BooleanOp) {
  builder.addFieldInt8(9, booleanOp, BooleanOp.None);
}

static addDataType(builder:flatbuffers.Builder, dataType:EntityData) {
  builder.addFieldInt8(10, dataType, EntityData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, dataOffset, 0);
}

static endElement(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
