// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Arc } from '../editor-data/arc.js';
import { Circle } from '../editor-data/circle.js';
import { Group } from '../editor-data/group.js';
import { Image } from '../editor-data/image.js';
import { Line } from '../editor-data/line.js';
import { Path } from '../editor-data/path.js';
import { Point } from '../editor-data/point.js';
import { Rect } from '../editor-data/rect.js';
import { Text } from '../editor-data/text.js';


export enum EntityData {
  NONE = 0,
  Point = 1,
  Line = 2,
  Rect = 3,
  Circle = 4,
  Arc = 5,
  Path = 6,
  Text = 7,
  Image = 8,
  Group = 9
}

export function unionToEntityData(
  type: EntityData,
  accessor: (obj:Arc|Circle|Group|Image|Line|Path|Point|Rect|Text) => Arc|Circle|Group|Image|Line|Path|Point|Rect|Text|null
): Arc|Circle|Group|Image|Line|Path|Point|Rect|Text|null {
  switch(EntityData[type]) {
    case 'NONE': return null; 
    case 'Point': return accessor(new Point())! as Point;
    case 'Line': return accessor(new Line())! as Line;
    case 'Rect': return accessor(new Rect())! as Rect;
    case 'Circle': return accessor(new Circle())! as Circle;
    case 'Arc': return accessor(new Arc())! as Arc;
    case 'Path': return accessor(new Path())! as Path;
    case 'Text': return accessor(new Text())! as Text;
    case 'Image': return accessor(new Image())! as Image;
    case 'Group': return accessor(new Group())! as Group;
    default: return null;
  }
}

export function unionListToEntityData(
  type: EntityData, 
  accessor: (index: number, obj:Arc|Circle|Group|Image|Line|Path|Point|Rect|Text) => Arc|Circle|Group|Image|Line|Path|Point|Rect|Text|null, 
  index: number
): Arc|Circle|Group|Image|Line|Path|Point|Rect|Text|null {
  switch(EntityData[type]) {
    case 'NONE': return null; 
    case 'Point': return accessor(index, new Point())! as Point;
    case 'Line': return accessor(index, new Line())! as Line;
    case 'Rect': return accessor(index, new Rect())! as Rect;
    case 'Circle': return accessor(index, new Circle())! as Circle;
    case 'Arc': return accessor(index, new Arc())! as Arc;
    case 'Path': return accessor(index, new Path())! as Path;
    case 'Text': return accessor(index, new Text())! as Text;
    case 'Image': return accessor(index, new Image())! as Image;
    case 'Group': return accessor(index, new Group())! as Group;
    default: return null;
  }
}
