// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ColorRGBA } from '../editor-data/color-rgba.js';
import { Gradient } from '../editor-data/gradient.js';


export enum FillData {
  NONE = 0,
  ColorRGBA = 1,
  Gradient = 2
}

export function unionToFillData(
  type: FillData,
  accessor: (obj:ColorRGBA|Gradient) => ColorRGBA|Gradient|null
): ColorRGBA|Gradient|null {
  switch(FillData[type]) {
    case 'NONE': return null; 
    case 'ColorRGBA': return accessor(new ColorRGBA())! as ColorRGBA;
    case 'Gradient': return accessor(new Gradient())! as Gradient;
    default: return null;
  }
}

export function unionListToFillData(
  type: FillData, 
  accessor: (index: number, obj:ColorRGBA|Gradient) => ColorRGBA|Gradient|null, 
  index: number
): ColorRGBA|Gradient|null {
  switch(FillData[type]) {
    case 'NONE': return null; 
    case 'ColorRGBA': return accessor(index, new ColorRGBA())! as ColorRGBA;
    case 'Gradient': return accessor(index, new Gradient())! as Gradient;
    default: return null;
  }
}
