// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GradientData, unionToGradientData, unionListToGradientData } from '../editor-data/gradient-data.js';


export class Gradient {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Gradient {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGradient(bb:flatbuffers.ByteBuffer, obj?:Gradient):Gradient {
  return (obj || new Gradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGradient(bb:flatbuffers.ByteBuffer, obj?:Gradient):Gradient {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Gradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

dataType():GradientData {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : GradientData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static getFullyQualifiedName(): "EditorData.Gradient" {
  return 'EditorData.Gradient';
}

static startGradient(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addDataType(builder:flatbuffers.Builder, dataType:GradientData) {
  builder.addFieldInt8(1, dataType, GradientData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dataOffset, 0);
}

static endGradient(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGradient(builder:flatbuffers.Builder, id:number, dataType:GradientData, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  Gradient.startGradient(builder);
  Gradient.addId(builder, id);
  Gradient.addDataType(builder, dataType);
  Gradient.addData(builder, dataOffset);
  return Gradient.endGradient(builder);
}
}
