// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { LinearGradient } from '../editor-data/linear-gradient.js';
import { RadialGradient } from '../editor-data/radial-gradient.js';


export enum GradientData {
  NONE = 0,
  LinearGradient = 1,
  RadialGradient = 2
}

export function unionToGradientData(
  type: GradientData,
  accessor: (obj:LinearGradient|RadialGradient) => LinearGradient|RadialGradient|null
): LinearGradient|RadialGradient|null {
  switch(GradientData[type]) {
    case 'NONE': return null; 
    case 'LinearGradient': return accessor(new LinearGradient())! as LinearGradient;
    case 'RadialGradient': return accessor(new RadialGradient())! as RadialGradient;
    default: return null;
  }
}

export function unionListToGradientData(
  type: GradientData, 
  accessor: (index: number, obj:LinearGradient|RadialGradient) => LinearGradient|RadialGradient|null, 
  index: number
): LinearGradient|RadialGradient|null {
  switch(GradientData[type]) {
    case 'NONE': return null; 
    case 'LinearGradient': return accessor(index, new LinearGradient())! as LinearGradient;
    case 'RadialGradient': return accessor(index, new RadialGradient())! as RadialGradient;
    default: return null;
  }
}
