// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ColorRGBA } from '../editor-data/color-rgba.js';


export class GradientStop {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GradientStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGradientStop(bb:flatbuffers.ByteBuffer, obj?:GradientStop):GradientStop {
  return (obj || new GradientStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGradientStop(bb:flatbuffers.ByteBuffer, obj?:GradientStop):GradientStop {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GradientStop()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

offset():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

color(obj?:ColorRGBA):ColorRGBA|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ColorRGBA()).__init(this.bb_pos + offset, this.bb!) : null;
}

static getFullyQualifiedName(): "EditorData.GradientStop" {
  return 'EditorData.GradientStop';
}

static startGradientStop(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOffset(builder:flatbuffers.Builder, offset:number) {
  builder.addFieldFloat32(0, offset, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, colorOffset, 0);
}

static endGradientStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
