// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Element } from '../editor-data/element.js';


export class Group {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Group {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGroup(bb:flatbuffers.ByteBuffer, obj?:Group):Group {
  return (obj || new Group()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGroup(bb:flatbuffers.ByteBuffer, obj?:Group):Group {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Group()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

children(index: number, obj?:Element):Element|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Element()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

childrenLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

clipContent():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static getFullyQualifiedName(): "EditorData.Group" {
  return 'EditorData.Group';
}

static startGroup(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addChildren(builder:flatbuffers.Builder, childrenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, childrenOffset, 0);
}

static createChildrenVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChildrenVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addClipContent(builder:flatbuffers.Builder, clipContent:boolean) {
  builder.addFieldInt8(1, +clipContent, +false);
}

static endGroup(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGroup(builder:flatbuffers.Builder, childrenOffset:flatbuffers.Offset, clipContent:boolean):flatbuffers.Offset {
  Group.startGroup(builder);
  Group.addChildren(builder, childrenOffset);
  Group.addClipContent(builder, clipContent);
  return Group.endGroup(builder);
}
}
