// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Image {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Image {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImage(bb:flatbuffers.ByteBuffer, obj?:Image):Image {
  return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImage(bb:flatbuffers.ByteBuffer, obj?:Image):Image {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

assetId():string|null
assetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
assetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static getFullyQualifiedName(): "EditorData.Image" {
  return 'EditorData.Image';
}

static startImage(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addAssetId(builder:flatbuffers.Builder, assetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, assetIdOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(1, width, 0.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(2, height, 0.0);
}

static endImage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createImage(builder:flatbuffers.Builder, assetIdOffset:flatbuffers.Offset, width:number, height:number):flatbuffers.Offset {
  Image.startImage(builder);
  Image.addAssetId(builder, assetIdOffset);
  Image.addWidth(builder, width);
  Image.addHeight(builder, height);
  return Image.endImage(builder);
}
}
