// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GradientStop } from '../editor-data/gradient-stop.js';
import { TileMode } from '../editor-data/tile-mode.js';
import { Vec2 } from '../editor-data/vec2.js';


export class LinearGradient {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LinearGradient {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLinearGradient(bb:flatbuffers.ByteBuffer, obj?:LinearGradient):LinearGradient {
  return (obj || new LinearGradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLinearGradient(bb:flatbuffers.ByteBuffer, obj?:LinearGradient):LinearGradient {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LinearGradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

end(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

stops(index: number, obj?:GradientStop):GradientStop|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new GradientStop()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tileMode():TileMode {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TileMode.Clamp;
}

static getFullyQualifiedName(): "EditorData.LinearGradient" {
  return 'EditorData.LinearGradient';
}

static startLinearGradient(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, endOffset, 0);
}

static addStops(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stopsOffset, 0);
}

static createStopsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTileMode(builder:flatbuffers.Builder, tileMode:TileMode) {
  builder.addFieldInt8(3, tileMode, TileMode.Clamp);
}

static endLinearGradient(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
