// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Matrix3x3 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Matrix3x3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

m00():number {
  return this.bb!.readFloat32(this.bb_pos);
}

m01():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

m02():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

m10():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

m11():number {
  return this.bb!.readFloat32(this.bb_pos + 16);
}

m12():number {
  return this.bb!.readFloat32(this.bb_pos + 20);
}

m20():number {
  return this.bb!.readFloat32(this.bb_pos + 24);
}

m21():number {
  return this.bb!.readFloat32(this.bb_pos + 28);
}

m22():number {
  return this.bb!.readFloat32(this.bb_pos + 32);
}

static getFullyQualifiedName(): "EditorData.Matrix3x3" {
  return 'EditorData.Matrix3x3';
}

static sizeOf():number {
  return 36;
}

static createMatrix3x3(builder:flatbuffers.Builder, m00: number, m01: number, m02: number, m10: number, m11: number, m12: number, m20: number, m21: number, m22: number):flatbuffers.Offset {
  builder.prep(4, 36);
  builder.writeFloat32(m22);
  builder.writeFloat32(m21);
  builder.writeFloat32(m20);
  builder.writeFloat32(m12);
  builder.writeFloat32(m11);
  builder.writeFloat32(m10);
  builder.writeFloat32(m02);
  builder.writeFloat32(m01);
  builder.writeFloat32(m00);
  return builder.offset();
}

}
