// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec2 } from '../editor-data/vec2.js';


export class Point {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Point {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPoint(bb:flatbuffers.ByteBuffer, obj?:Point):Point {
  return (obj || new Point()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPoint(bb:flatbuffers.ByteBuffer, obj?:Point):Point {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Point()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pos(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

static getFullyQualifiedName(): "EditorData.Point" {
  return 'EditorData.Point';
}

static startPoint(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, posOffset, 0);
}

static endPoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPoint(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset):flatbuffers.Offset {
  Point.startPoint(builder);
  Point.addPos(builder, posOffset);
  return Point.endPoint(builder);
}
}
