// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GradientStop } from '../editor-data/gradient-stop.js';
import { TileMode } from '../editor-data/tile-mode.js';
import { Vec2 } from '../editor-data/vec2.js';


export class RadialGradient {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RadialGradient {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRadialGradient(bb:flatbuffers.ByteBuffer, obj?:RadialGradient):RadialGradient {
  return (obj || new RadialGradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRadialGradient(bb:flatbuffers.ByteBuffer, obj?:RadialGradient):RadialGradient {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RadialGradient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

center(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

stops(index: number, obj?:GradientStop):GradientStop|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new GradientStop()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stopsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tileMode():TileMode {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TileMode.Clamp;
}

static getFullyQualifiedName(): "EditorData.RadialGradient" {
  return 'EditorData.RadialGradient';
}

static startRadialGradient(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addCenter(builder:flatbuffers.Builder, centerOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, centerOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(1, radius, 0.0);
}

static addStops(builder:flatbuffers.Builder, stopsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, stopsOffset, 0);
}

static createStopsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStopsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTileMode(builder:flatbuffers.Builder, tileMode:TileMode) {
  builder.addFieldInt8(3, tileMode, TileMode.Clamp);
}

static endRadialGradient(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRadialGradient(builder:flatbuffers.Builder, centerOffset:flatbuffers.Offset, radius:number, stopsOffset:flatbuffers.Offset, tileMode:TileMode):flatbuffers.Offset {
  RadialGradient.startRadialGradient(builder);
  RadialGradient.addCenter(builder, centerOffset);
  RadialGradient.addRadius(builder, radius);
  RadialGradient.addStops(builder, stopsOffset);
  RadialGradient.addTileMode(builder, tileMode);
  return RadialGradient.endRadialGradient(builder);
}
}
