// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Rect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Rect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRect(bb:flatbuffers.ByteBuffer, obj?:Rect):Rect {
  return (obj || new Rect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRect(bb:flatbuffers.ByteBuffer, obj?:Rect):Rect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Rect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

cornerRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static getFullyQualifiedName(): "EditorData.Rect" {
  return 'EditorData.Rect';
}

static startRect(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(0, width, 0.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(1, height, 0.0);
}

static addCornerRadius(builder:flatbuffers.Builder, cornerRadius:number) {
  builder.addFieldFloat32(2, cornerRadius, 0.0);
}

static endRect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRect(builder:flatbuffers.Builder, width:number, height:number, cornerRadius:number):flatbuffers.Offset {
  Rect.startRect(builder);
  Rect.addWidth(builder, width);
  Rect.addHeight(builder, height);
  Rect.addCornerRadius(builder, cornerRadius);
  return Rect.endRect(builder);
}
}
