// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Element } from '../editor-data/element.js';
import { Gradient } from '../editor-data/gradient.js';


export class Scene {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Scene {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScene(bb:flatbuffers.ByteBuffer, obj?:Scene):Scene {
  return (obj || new Scene()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScene(bb:flatbuffers.ByteBuffer, obj?:Scene):Scene {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Scene()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

version():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

canvasWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

canvasHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

gradients(index: number, obj?:Gradient):Gradient|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Gradient()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

gradientsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rootElements(index: number, obj?:Element):Element|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Element()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rootElementsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static getFullyQualifiedName(): "EditorData.Scene" {
  return 'EditorData.Scene';
}

static startScene(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt32(0, version, 0);
}

static addCanvasWidth(builder:flatbuffers.Builder, canvasWidth:number) {
  builder.addFieldFloat32(1, canvasWidth, 0.0);
}

static addCanvasHeight(builder:flatbuffers.Builder, canvasHeight:number) {
  builder.addFieldFloat32(2, canvasHeight, 0.0);
}

static addGradients(builder:flatbuffers.Builder, gradientsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, gradientsOffset, 0);
}

static createGradientsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGradientsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRootElements(builder:flatbuffers.Builder, rootElementsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, rootElementsOffset, 0);
}

static createRootElementsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRootElementsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endScene(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSceneBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSceneBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createScene(builder:flatbuffers.Builder, version:number, canvasWidth:number, canvasHeight:number, gradientsOffset:flatbuffers.Offset, rootElementsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Scene.startScene(builder);
  Scene.addVersion(builder, version);
  Scene.addCanvasWidth(builder, canvasWidth);
  Scene.addCanvasHeight(builder, canvasHeight);
  Scene.addGradients(builder, gradientsOffset);
  Scene.addRootElements(builder, rootElementsOffset);
  return Scene.endScene(builder);
}
}
