// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Text {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Text {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsText(bb:flatbuffers.ByteBuffer, obj?:Text):Text {
  return (obj || new Text()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsText(bb:flatbuffers.ByteBuffer, obj?:Text):Text {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Text()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fontSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

fontFamily():string|null
fontFamily(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fontFamily(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

letterSpacing():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

lineHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static getFullyQualifiedName(): "EditorData.Text" {
  return 'EditorData.Text';
}

static startText(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, contentOffset, 0);
}

static addFontSize(builder:flatbuffers.Builder, fontSize:number) {
  builder.addFieldFloat32(1, fontSize, 0.0);
}

static addFontFamily(builder:flatbuffers.Builder, fontFamilyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fontFamilyOffset, 0);
}

static addLetterSpacing(builder:flatbuffers.Builder, letterSpacing:number) {
  builder.addFieldFloat32(3, letterSpacing, 0.0);
}

static addLineHeight(builder:flatbuffers.Builder, lineHeight:number) {
  builder.addFieldFloat32(4, lineHeight, 0.0);
}

static endText(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createText(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset, fontSize:number, fontFamilyOffset:flatbuffers.Offset, letterSpacing:number, lineHeight:number):flatbuffers.Offset {
  Text.startText(builder);
  Text.addContent(builder, contentOffset);
  Text.addFontSize(builder, fontSize);
  Text.addFontFamily(builder, fontFamilyOffset);
  Text.addLetterSpacing(builder, letterSpacing);
  Text.addLineHeight(builder, lineHeight);
  return Text.endText(builder);
}
}
